### ISSUE TITLE
Calling refetch causes the calling component to be destroyed and lose internal state

### ISSUE THREAD

**Issue by saikat** [apollostack/react-apollo#113]
Whenever you call refetch on some data, the entire component seems to get destroyed and recreated, losing any internal state that was being kept on the component.  Not sure if there is a workaround for this behavior for now.

**Comment by stubailo** [comment]
Did this resolve itself somehow? I assume this is no longer an issue since it's closed.

**Comment by saikat** [comment]
Yes, was a late night oversight on my part.  Did not realize I had a wrapper component in between that was removing and recreating the component.  Sorry!
