### ISSUE TITLE
Are there plans to support server side rendering?

### ISSUE THREAD

**Issue by ads1018** [apollostack/react-apollo#114]

**Comment by ads1018** [comment]
Apologies, I somehow glossed over this section the the apollo-client docs: http://docs.apollostack.com/apollo-client/index.html#store-rehydration.

**Comment by jbaxleyiii** [comment]
@ads1018 we also just landed early support for auto SSR with #83. Still a few bugs to work out, but all in all its working well

**Comment by ads1018** [comment]
Fantastic!
