### ISSUE TITLE
How to use watchQueries?

### ISSUE THREAD

**Issue by danielbuechele** [apollostack/react-apollo#116]
I am wondering how I can connect a component using a watchQuery. I connected my component like this, which is working, but I don't get an update after the mutation is executed. This is why I think I should switch to watchQueries. However, I am not sure how to transform this code to create a watchQuery. I can add a `pollInterval` which is also working, but I am wondering if there isn't a better way to display the result of the mutation.

```
export default connect({
	mapQueriesToProps: ({ ownProps, state }) => ({
		store: {
			query: gql`
				...
			`,
		},
	}),
	mapMutationsToProps: ({ ownProps, state }) => ({
		saveItem: item => ({
			mutation: gql`
				...
			`,
		}),
	}),
})(EditRoute);
```

**Comment by stubailo** [comment]
`watchQuery` doesn't automatically get an update after a mutation completes. We're still working on the final API for that. Right now the best option is to use `refetch` or `pollInterval`, but we should have something better this week.

`connect` _does_ use watchQuery, so it's identical to the results you would get from it.

**Comment by Fercho191** [comment]
I need to understand how it is used, @stubailo  can you explain?
