### ISSUE TITLE
Update error interface to be compatible with 0.4.x ApolloError

### ISSUE THREAD

**Issue by timbotnik** [apollostack/react-apollo#117]
@stubailo shouldn't we should change the `errors` property to be a single `error` object of type `ApolloError`?  Also, not sure what we should see in the console, but I'm getting:
![screen shot 2016-07-19 at 1 25 09 pm](https://cloud.githubusercontent.com/assets/1831709/16937661/50490630-4db4-11e6-8295-65867b5bce1e.png)

**Comment by jbaxleyiii** [comment]
@timbotnik I'm going to get this into the next milestone
