### ISSUE TITLE
Wrapped component instance accessor

### ISSUE THREAD

**Issue by rstuven** [apollostack/react-apollo#118]
react-redux has [a getWrappedInstance method and a withRef option](https://github.com/reactjs/react-redux/blob/master/docs/api.md#getwrappedinstance-reactcomponent). These can be helpful if we want to access [exposed component functions](https://facebook.github.io/react/tips/expose-component-functions.html).

If I pass `withRef: true` to apollo-react's `connect` options, I only get access to the `ApolloConnect` wrapped instance, but there is no way to access my component wrapped instance.

**Comment by stubailo** [comment]
Did we do this one?

**Comment by richburdon** [comment]
Same here

**Comment by richburdon** [comment]
For documentation purposes: if compose() is used to wrap multiple containers (i.e., Redux and multiple graphql calls). then getWrappedInstance has to be chained to reach the underlying component. 

(This is obvious in hindsight, but I feel that compose could be given an option to automatically cascade the reference to the outer container. Or at least document the hint here: http://dev.apollodata.com/react/higher-order-components.html#compose)

**Comment by tmeasday** [comment]
@richburdon perhaps you could send a PR to that doc? We just take compose from the recompose library.
