### ISSUE TITLE
Can we add SSR integration to docs?

### ISSUE THREAD

**Issue by ads1018** [apollostack/react-apollo#119]
I noticed support for SSR was merged into master with #83. I'm really looking forward to integrating server side rendering in my apollo stack application but I'm not quite sure how to implement it!

**Comment by jbaxleyiii** [comment]
@ads1018 you bet! I've shipped it silently to make sure it is all working great before documenting it. With the upcoming 0.4.0 API changes, we will be redoing a lot of the docs!

**Comment by ads1018** [comment]
Fantastic! You guys are the best. I <3 apollo.
