### ISSUE TITLE
isEqual

### ISSUE THREAD

**Issue by nevir** [apollostack/react-apollo#121]
In a few places, `@connect` is relying on [`_.isEqual`](https://lodash.com/docs#isEqual) to compare values:

* [In `componentWillReceiveProps`](https://github.com/apollostack/react-apollo/blob/master/src/connect.tsx#L205) to check for props differences since last render.
* [In the store observer](https://github.com/apollostack/react-apollo/blob/master/src/connect.tsx#L264) comparing the _entire store state_ to the previous state every time the store changes, per connected component.
* and a few more that are probably less relevant

The reason I bring this up is that lodash's `isEqual` performs a **deep** equality check.  

For the two checks above, it seems like a shallow check would be sufficient (and may have been intended)?  I suspect this may be a pretty big perf hot spot

**Comment by stubailo** [comment]
I'm pretty worried about looking at code to find suspected hotspots - is there some way we can run tests in a production-like environment to find out which hotspots are the most important during real execution?

**Comment by nevir** [comment]
I wasn't auditing for perf; just ran into these when trying to understand
some of the logic - using deep equality comparisons just didn't seem like
the intention of that code

**Comment by stubailo** [comment]
That's true - we should ask @jbaxleyiii if those are necessary or intended.

> I suspect this may be a pretty big perf hot spot

This is the part I was responding to.

**Comment by jbaxleyiii** [comment]
@nevir @stubailo I've reduced a number of these in the 1.0.0

**Comment by nevir** [comment]
Sweet!

**Comment by MichaelHilus** [comment]
I just found, that isEqual(...) is returning true for two unequal Date objects. Or am I wrong?
See attached screenshot the debugger in chrome:

![image](https://user-images.githubusercontent.com/20665077/27373925-4e9dc824-566a-11e7-8c93-4af52f9ef985.png)

Found this on debugging because my queries were not fired after variables change.
