### ISSUE TITLE
Nested fields in fragments not passed to props.

### ISSUE THREAD

**Issue by jordan-burnett** [apollostack/react-apollo#124]
When using multiple fragments, I'm finding that nested fields aren't being resolved to props as expected.

For example, I have a query attached to a connected component like:

```
neighbourhoods{
   name
   ...fragmentOne
   ...fragmentTwo
}
```

with two fragments like:

```
fragment fragmentOne on Neighbourhood {
    population
    city {
        name
    }
}
```
```
fragment fragmentOne on Neighbourhood {
    city {
        countryName
    }
}
```

I can see in the server response city.name and city.countryName is returned as expected for each neighbourhood, but my component only seems to receive the data from the first fragment in it's props and I'm only able to see city.name.  Is this the expected behaviour?

**Comment by stubailo** [comment]
Definitely not expected! Fragments are relatively new so there might be a few bugs. It would be really helpful to have a more complete code snippet of how you declared the fragment and included it in the query to debug this though.

**Comment by jordan-burnett** [comment]
No problem, here's a compressed version of the code I'm using which I've just tested produces the same result:

```
const fragmentOne = createFragment(gql`
  fragment fragmentOne on Neighbourhood {
    name
    city {
      name
      population
    }
  }
`);

const fragmentTwo = createFragment(gql`
  fragment fragmentTwo on Neighbourhood {
    id
    city {
      countryName
      image
    }
  }
`);

function mapQueriesToProps({ ownProps, state }) {
  return {
    neighbourhood: {
      query: gql`
        query neighbourhoodData($slug: String!) {
          data: neighbourhood(slug: $slug) {
            title
            subtitle
            ...fragmentOne
            ...fragmentTwo
          }
        }`,
      variables: {
        slug: ownProps.params.slug,
      },
      fragments: [...fragmentOne, ...fragmentTwo]
    },
  };
};


class Component extends React.Component {
  render() {
    if(this.props.neighbourhood.data) {
      const data = this.props.neighbourhood.data;
      console.log(data); // <-- Here city only contains 'name' and 'population'
    }
   return null;
  }
}

const ConnectedComponent = connect({
  mapQueriesToProps
})(Component);
```

The order in the root query changes the output.  If I place fragmentTwo first then city contains 'countryName' and 'image'

**Comment by jbaxleyiii** [comment]
@stubailo I'm assuming this is a client issue?

**Comment by stubailo** [comment]
Ah, I think we missed it because it was on this repo. Just opened an issue there, let's close this one.
