### ISSUE TITLE
redux coupling?

### ISSUE THREAD

**Issue by pkieltyka** [apollostack/react-apollo#125]
Hello,

Just wondering if you've considered a flux-agnostic library for react? For example, our app is written using mobxjs, which is also picking up huge popularity for its productivity and simplicity for managing state in js/react apps, and I've been checking out apollo to use with our app. If you have plans / thoughts on this that would be much appreciated. And thanks for Apollo, its very nice work that simplifies getting into graphql big time.

**Comment by jbaxleyiii** [comment]
@pkieltyka actually yes! Take a look at #120 ! It should be done pretty soon!

**Comment by pkieltyka** [comment]
@jbaxleyiii awesome! thanks
