### ISSUE TITLE
"Reactive" updates

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/react-apollo#126]
Guys, would you be keen on sharing a full example on how would you approach "reactive" updates of react ui via watchquery? It's not very clear. It would be a great addition also to official documentation.

Scenario is simple.

1. I paint my react ui with data fetched via Apollo
2. On server data is changed via another user's mutation
3. Data travels to the observing client and ui is repainted

Any help is greatly appreciated

**Comment by stubailo** [comment]
This is definitely not trivial, since GraphQL doesn't currently have any features about realtime updates from the server. We are working on an experimental "GraphQL subscriptions" feature though that might provide some of this functionality, hopefully it will be usable in about two weeks.

**Comment by jbaxleyiii** [comment]
Closing until subscriptions are ready
