### ISSUE TITLE
Redux connect + Pagination

### ISSUE THREAD

**Issue by BenjaminThong** [apollostack/react-apollo#128]
Hi, 

it would be great if there was an example on pagination via Redux connect().

Also the existing pagination examples on the Apollo-client documentation don't show the schema used on the server side.

Are Relay styled edges/node connections supported?

Thank you :)

**Comment by Slava** [comment]
Can you please be more specific? What would an example with Redux connect show? Why is it important?

**Comment by jbaxleyiii** [comment]
@BenjaminThong here is an example of using `fetchMore` to query the endpoint again with new variables. https://github.com/apollostack/react-apollo/blob/master/test/react-web/client/graphql/queries.tsx#L538-L545

Apollo can use any kind of valid GraphQL server so edges and nodes are supported. We use nodes with our server right now and it works great!

If you have a relay compliant server that has cursor based pagination, you could supply the `next` or `after` as new variables on the `fetchMore` call.

Does that help?

**Comment by BenjaminThong** [comment]
thanks @jbaxleyiii , things are much clearer now. Cheers!
