### ISSUE TITLE
updateQueries is not updating queries for mutations

### ISSUE THREAD

**Issue by scottmcpherson** [apollostack/react-apollo#129]
We had a debugging session on the [slack Apollo Stack #general channel](https://apollostack.slack.com/archives/general/p1470260863002725). We were unable to get `updateQueries` to fire and update the queries. 

I tried several approaches but the two main one were:
- [define `updateQueries` in `mapMutationsToProps`] (https://github.com/scottmcpherson/meteor-starter-kit/blob/51084e6064ab825d9ad99b8b6baf807e2e2d05df/imports/ui/Tasks.js#L70)
- [and call `client.mutate` directly](https://github.com/scottmcpherson/meteor-starter-kit/blob/master/imports/ui/Tasks.js#L17)

Both of those approaches are on separate commits for reference:

mapMutationsToProps: https://github.com/scottmcpherson/meteor-starter-kit/tree/51084e6064ab825d9ad99b8b6baf807e2e2d05df

client.mutate: https://github.com/scottmcpherson/meteor-starter-kit

**Comment by Slava** [comment]
It seems like your query is unnamed? https://github.com/scottmcpherson/meteor-starter-kit/blob/master/imports/ui/Tasks.js#L74-L80

Your query name should match what you are updating. So in your case it will be:

```gql
            query tasks {
              tasks {
                _id
                title
              }
            }
```

**Comment by sntran** [comment]
@scottmcpherson were you able to get `updateQueries` working by naming your query? I could not get it run either. `updateQueries` never fired for me, even with named query.

**Comment by scottmcpherson** [comment]
No, unfortunately not @sntran. Instead, I used a combination of polling and calling refetch on the data. My repo is up to date if you want to check it out

**Comment by Slava** [comment]
@scottmcpherson I would like to dig into the origin of your problem. Can you please help me to gather more information? A smaller reproduction demonstrating the issue would help a lot.

**Comment by sntran** [comment]
@jbaxleyiii , I have updated to `0.4.x` and can verify that `updateQueries` work as expected. Thanks for the update!
