### ISSUE TITLE
Check error handling

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-apollo#13]
Doesn't work in example app

**Comment by jbaxleyiii** [comment]
@stubailo which parts in particular? Do you have an example?

**Comment by stubailo** [comment]
yeah let me whip up an example

**Comment by stubailo** [comment]
https://github.com/apollostack/meteor-starter-kit/pull/1

You can look in the redux dev tools, and the error is in there - maybe the client itself somehow never reports it?

**Comment by jbaxleyiii** [comment]
on it!

**Comment by stubailo** [comment]
I'm going to go to sleep, then get back at it tomorrow morning! We're really getting somewhere, funny that these things don't really come up until you put them all together :]

**Comment by stubailo** [comment]
Let me know if you learn anything, and I can pick it up then!

**Comment by jbaxleyiii** [comment]
found and fixed with https://github.com/apollostack/react-apollo/pull/16.

I'll add in a test tomorrow 👍
