### ISSUE TITLE
Should I expect the same error handling as `apollo-client`?

### ISSUE THREAD

**Issue by deoqc** [apollostack/react-apollo#130]
Well, these two are the *same*?

```Javascript
apollo.mutate({
  mutation,
  variables,
})
```
or...
```Javascript
const mapMutationsToProps = ...
...
this.props.mutations.myMutation()
```

Now, the `apollo-client` throw errors with graphQLErrros array and message inside it, but `react-apollo` is throwing and the object is somewhat strange.

It seems they should behave equals, but if not, what are to be the differences?

**Comment by stubailo** [comment]
I think this might be a bug: https://github.com/apollostack/react-apollo/issues/117

Those are definitely expected to be the same.

**Comment by jbaxleyiii** [comment]
@deoqc @stubailo yeah the current release has not updated to support the new error syntax. I'll get that out soon

**Comment by deoqc** [comment]
Thanks a lot @stubailo @jbaxleyiii .

Just one more thing: could we expect some major changes in the current error handling api for `apollo-client`?

It used not to throw, now it is throwing (I didn't consider it a bug, I thought it were the intended behaviour); the errors are in a graphQLErrors, etc... Just wondering if this is kind of stable now, or should we expect (major?) changes like these.

**Comment by stubailo** [comment]
We're hoping to release a stable version in the coming months (before the end of the year for sure) and then we won't change it anymore. Until then, I think it is unlikely to change but it's possible.

**Comment by deoqc** [comment]
Thanks @stubailo @jbaxleyiii
