### ISSUE TITLE
Is there a way to do some validation before sending queries/mutations?

### ISSUE THREAD

**Issue by sammkj** [apollostack/react-apollo#131]
My use case is I wanna check if JWT token is still valid before sending queries to server like how we are able to use middleware in the `networkInterface`.

**Comment by stubailo** [comment]
Could you do this using a network interface middleware? You can do anything you want in there, and the function runs before every single request.

**Comment by jbaxleyiii** [comment]
@sammkj the new API ( #120 ) allows you to set `skip: true` on a query to bypass it based on information. If you can't use the network interface middleware, this is a place you could do that.
