### ISSUE TITLE
loading frequently gets stuck true during refetches

### ISSUE THREAD

**Issue by nevir** [apollostack/react-apollo#133]
On react-apollo `0.3.20`, we're seeing behavior where `loading` state is stuck to `true` upon calling `refetch()`. Same behavior also occurs when there are errors from the server (the `error` persists even if the query succeeds later on). The state becomes reset when _another_  `@connect`ed component triggers a query.

Unfortunately, it's not 100% reproducible; and I'm not sure exactly what combination of factors is causing it yet

**Comment by nevir** [comment]
It may also be related to https://github.com/apollostack/apollo-client/pull/524 ?

**Comment by nevir** [comment]
Tracked it down. It's purely a problem with our use of react-apollo; nothing to see here!

(There was a bug in https://github.com/apollostack/apollo-client/pull/446, fixed via https://github.com/apollostack/apollo-client/pull/446/commits/39d798f2b587f62b07f8b82794576e7ec29c6897)

**Comment by iktl** [comment]
@nevir What was the issue you had with your implementation, believe we are hitting the same.
