### ISSUE TITLE
Support for fragments

### ISSUE THREAD

**Issue by deoqc** [apollostack/react-apollo#143]
Two issues:
- Problem, but not sure if in this integration or in react-client;
- Feature request;

#### - Problem

I tried to use fragments but got error `undefined is not an object (evaluating 'definition.kind')` in line 46 of `getFromAST.js`.

I'm doing a standard thing:
```Javascript
graphql(query, { options: () => ({ fragments }) })
```

Where fragments is a list of:
```Javascript
createFragment(gql`
  fragment MyName on MyObject {
   ...
  }
`)
```

#### - Feature request

`options` could also receive a object, instead of only a function returning a object. So avoid, `options: () => ({ fragments })`, for example. It's quite common to do this, like in [recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md).

**Comment by jbaxleyiii** [comment]
@deoqc this *should* work as is currently? Can you show any more of your app?

I think allowing an object for options would be helpful! I'll work on that. Could you open it as a separate issue?

**Comment by jbaxleyiii** [comment]
@deoqc would you be able to show your component / enhancer code?

**Comment by deoqc** [comment]
@jbaxleyiii I did a silly mistake (`export const` instead of `export default`) and were passing `undefined` as one of fragments.

As a suggestion, the component could check if fragment is the expected object and return a nice error message if it's not.

thx for the usual fast help.

**Comment by stubailo** [comment]
I think this is indeed an error in apollo client - we should have a nicer message here. Opened an issue about it if anyone wants to contribute: https://github.com/apollostack/apollo-client/issues/546
