### ISSUE TITLE
Feature Request - Options as object

### ISSUE THREAD

**Issue by deoqc** [apollostack/react-apollo#144]
Originally posted [here](https://github.com/apollostack/react-apollo/issues/143).

---

`options` could also receive a object, instead of only a function returning a object. So avoid, `options: () => ({ fragments })`, for example. 

It's quite common to do this, like in [recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md). Also, it could be a general pattern for anything returning an object.

**Comment by jbaxleyiii** [comment]
Added in the next release!
