### ISSUE TITLE
[Batching] Can't find field X on result object ROOT_QUERY. when activating batching with two queries on the same component

### ISSUE THREAD

**Issue by rricard** [apollostack/react-apollo#146]
I have two different queries `connect`ed to a same component and use fragments, let's say:

```js
const CompWithData = connect({
  mapQueriesToProps: () => ({
    q1: {query: gql`{ ...FragmentWithField1 }`, fragments: fField1, pollInterval: 30000}, // in my setup, I'm polling but this may not do anything
    q2: {query: gql`{ field2 }`},
  }),
})(Comp);
```

This works perfectly well usually, but if I activate query batching on the apollo client, things start to go bad:

I will get an error like this without a stack, completely crashing redux: `Can't find field field1 on result object ROOT_QUERY`.

Here is what my redux devtool looks like:

<img width="833" alt="robin_ricard_and_home_thedesktop_io_ _batching-benchmark__origin_batching-benchmark__15916_commits_" src="https://cloud.githubusercontent.com/assets/246520/17697116/1b451e78-63b3-11e6-8964-71621c050cf4.png">

After that, redux is just unusable...

<img width="830" alt="robin_ricard" src="https://cloud.githubusercontent.com/assets/246520/17697155/59969a4e-63b3-11e6-8cb3-c6eb8fcb2690.png">

I don't know if it's react-apollo or apollo-client that's triggering this but this is the setup that triggers that for me.

> **EDIT** I have both latest versions for react-apollo and apollo-client
> Added some fragments since it is closer to what I actually have

**Comment by jbaxleyiii** [comment]
@rricard the latest version of react Apollo doesn't have `connect`. Although this sounds more like an apollo-client bug

**Comment by rricard** [comment]
@jbaxleyiii I managed to upgrade to the latest version and my `connect` calls were still working, either a cache was left either there is still the deprecated method. However, I think there is still an issue with batching and having two queries on the same component.

**Comment by rricard** [comment]
It seems linked to apollo-client but I have hard time reproducing this situation there and only there.

**Comment by voodooattack** [comment]
@jbaxleyiii If it's any help: I've noticed that this only happens with fragments and batching enabled in my case. When I remove fragments from the query everything works.

I'm using `react-apollo: 0.4.5` and `apollo-client: 0.4.11`.

**Comment by rricard** [comment]
@voodooattack yup, thank you for the precision, I'm in the same situation...

**Comment by crubier** [comment]
I am not using fragments but I have the same problem here with react-apollo: 0.4.5 and apollo-client: 0.4.11.

**Comment by rricard** [comment]
@jbaxleyiii I'll try to work on that once I managed to upgrade to 0.4.x, even if it's triggered by the apollo-client, I need to have the latest setup to clearly assess this.

**Comment by jbaxleyiii** [comment]
@rricard @crubier I think this was fixed with https://github.com/apollostack/apollo-client/pull/509

Can you confirm?

**Comment by rricard** [comment]
@jbaxleyiii I'm migrating to the latest react-apollo today, will tell you if it does, thanks!

**Comment by rricard** [comment]
Doesn't work just yet with
- apollo-client 0.4.12
- react-apollo 0.3.20

I'll now try to upgrade react-apollo

**Comment by jbaxleyiii** [comment]
@rricard dang

**Comment by rricard** [comment]
@jbaxleyiii lemme try more stuff, if that doesn't work, I may come back with more diagnosis info and if I have time, I'll try to fix it by debugging it myself inside the apollo code and maybe provide a patch.

**Comment by rricard** [comment]
but I think I'll have to come up with a test case!

**Comment by rricard** [comment]
@jbaxleyiii the migration to the newest react-apollo is not trivial, it'll take time

**Comment by jbaxleyiii** [comment]
@rricard I totally understand! We are still migrating ourselves

**Comment by crubier** [comment]
Still not working, with the last versions. Here is a minimal example:

```

// Create network interface
const networkInterface = createNetworkInterface('/graphql');

const client = new ApolloClient({
    networkInterface: networkInterface,
    //  initialState: window.__APOLLO_CONTEXT__ // If we use server-side rendering in the future, see http://docs.apollostack.com/apollo-client/#store-rehydration
});


// The redux reducer is created by combining the Apollo one with custom ones
const store = createStore(combineReducers({
    redux: myReducer, // A custom reducer
    apollo: client.reducer(), // The apollo reducer
}), applyMiddleware(client.middleware()));




/////////////////////////////////////////////////////////////////////
// Use the client directly
// THIS WORKS
// async function test() {
//     let res = await client.query({query: gql `
//     {
//       user {
//         firstName,
//         lastName
//       }
//     }`});
//     console.log('Query ', res);
//     let res2 = await client.mutate({
//         mutation: gql `
//       mutation modifyTheUser($firstName: String!, $lastName: String!) {
//         modifyUser(firstName: $firstName, lastName: $lastName) {
//           firstName
//           lastName
//       }
//     }`,
//         variables: {
//             firstName: "Bobbie",
//             lastName: "Joe"
//         }
//     });
//     console.log('Mutation ', res2);
// }
// test();



/////////////////////////////////////////////////////////////////////
// For graphql
// Down
const myQuery = gql `
  query getUser {
    user {
      firstName,
      lastName
    }
  }
`;
const MyComponentWithQuery = graphql(myQuery, {
    props: ({ownProps, data}) => {
        if (data.loading)
            return {userLoading: true};
        if (data.error)
            return {hasErrors: true};
        return {user: data.user, refetchUser: data.refetch};
    }
})(MyComponent);
// Up
const myMutation = gql `
  mutation modifyTheUser($firstName: String!, $lastName: String!) {
    modifyUser(firstName: $firstName, lastName: $lastName) {
      firstName
      lastName
    }
  }
`;
const MyComponentWithMutation = graphql(myMutation, {
    props: ({ownProps, mutate}) => ({
        async onMyMutationTriggered() {
            try {
                console.log("Triggered", ownProps);
                let {data} = await mutate({
                    variables: {
                        firstName: "Bobbie",
                        lastName: "Joe"
                    },
                    optimisticResponse: {
                        firstName: "Bobbie",
                        lastName: "Joe"
                    }
                });
                console.log("Success", data);
            } catch (error) {
                console.log("Error", error);
            }
        }
    })
})(MyComponentWithQuery);



/////////////////////////////////////////////////////////////////////
// For redux
// Down
const mapStateToProps = (state) => ({count: state.redux.counter});
// Up
const mapDispatchToProps = (dispatch) => {
    return {
        onIncrementButtonClicked: () => {
            dispatch(increment(2))
        }
    }
}
// Apply  redux to the component
const MyComponentWithData = connect(mapStateToProps, mapDispatchToProps)(MyComponentWithMutation);

/////////////////////////////////////////////////////////////////////
// Render everything
render(
    <ApolloProvider store={store} client={client}>
      <MyComponentWithData/>
    </ApolloProvider>,
 document.getElementById("root"))

```

**Comment by rricard** [comment]
@jbaxleyiii I'm not sure but it has been a few days I'm waiting for one of my PRs to be published in the latest client. Look at the changelog there, the fix you are talking about may still be scheduled for vNext...

**Comment by msimulcik** [comment]
@crubier, I had similar problem and in my case it was caused by `optimisticResponse`. Try  your example with modified `optimisticResponse` object:
```
optimisticResponse: {
    modifyUser: {
        firstName: "Bobbie",
        lastName: "Joe"
    }
}
```

**Comment by crubier** [comment]
@msimulcik Thank you so much, you are absolutely right ! 

@jbaxleyiii You can forget about my last messages, the problem is solved on my side !

Thank you very much every one, and sorry for polluting this thread.

**Comment by rricard** [comment]
@jbaxleyiii will retry once https://github.com/apollostack/apollo-client/pull/584 is merged (this PR covers a bug that breaks my batching anyway!)

**Comment by jbaxleyiii** [comment]
@rricard is this still an issue?

**Comment by rricard** [comment]
@jbaxleyiii oh! Need to check! Had a lot of stuff going on, will try now!

**Comment by jbaxleyiii** [comment]
@rricard any updates on this?

**Comment by rricard** [comment]
@jbaxleyiii : Good question, last time I tried, I had issues with something else. I'll just close this one and reopen one if I still get issues. Thanks!
