### ISSUE TITLE
Pre-step of restructuring / modifying the props before composing

### ISSUE THREAD

**Issue by bompi88** [apollostack/react-apollo#148]
Hi, I'm wondering whether it is possible to restructure / modify the props as a pre-step before composing a component when using `graphql` from `react-apollo`? 

I have the scenario below where I query for a list of contacts. The `jobTitle`variable of a contact contains a key I use to look up i18n translations using a meteor package `TAPi18n`. The `setData` method illustrates what I want to do, in a manner.

``` js
import ContactList from '../components/contact_list';
import { TAPi18n } from 'meteor/tap:i18n';
import { composeAll } from 'mantra-core';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

const GET_CONTACTS = {
  query: gql`
    query contacts {
      contacts {
        fullName,
        jobTitle,
        email,
        phone
      }
    }`,
  options: () => ({
    pollInterval: 60000,
    setData: (data) => {
      return {
        contacts: data.contacts && data.contacts.map((contact) => {
          contact.jobTitle = TAPi18n.__(contact.jobTitle);
          return contact;
        })
      };
    }
  })
};

export default composeAll(
  graphql(GET_CONTACTS.query, { options: GET_CONTACTS.options })
)(ContactList);
```

**Comment by jbaxleyiii** [comment]
@bompi88 Are you wanting to change the shape of the props that get sent to the child component? If so take a look at http://docs.apollostack.com/apollo-client/react.html#graphql-props

Otherwise, I'm not sure I follow

**Comment by bompi88** [comment]
@jbaxleyiii thanks, i must have overlooked it while reading the docs. It seems that I have to put the logic I wanted inside the component anyways, as I did not manage to reactively update the props while the language changes. If you have any suggestions I'd be very grateful. Thanks again :)

**Comment by jbaxleyiii** [comment]
Ah, I see. If the user changes their language, you want to translate the query result, not requery the server? Yeah I think that is best inside the component
