### ISSUE TITLE
options pollinterval after remount doesn't work

### ISSUE THREAD

**Issue by pfulop** [apollostack/react-apollo#149]
Hi,

So I have noticed today another problem that comes from remounting a component (again same principle let's say we reroute and come back, the component was mounter->unmounted->mounted).

When using pollInterval this is what happens:

- 1st mount: query is refetched every `interval` seconds : pass
- umount: query is stopped from refetching: pass
- 2nd mount: queries is still stopped from refetching : fail

To me it seems to me that queries are created on first mount only and destroyed on unmount, but when remount happens the query is not recreated or something.

Can't it somehow be related to [this line](https://github.com/apollostack/react-apollo/blob/f0da04fb94626de4c5ba46a2851f9f90d1321966/src/graphql.tsx#L361)? From what I see the code checks if there are new props, and if so, it will subscribe to query only after that, but in polling I don't think there is necessity for new props.

**Comment by BLamy** [comment]
Just noticed this issue myself.

**Comment by jbaxleyiii** [comment]
@pfulop @BLamy can you see in the network panel if requests are still going out? If the data doesn't change, the child component won't update because no props have changed

**Comment by jbaxleyiii** [comment]
I added a test case for this (which is working as expected) in #150

**Comment by pfulop** [comment]
No the request are not going out since the polling is not active.

**Comment by jbaxleyiii** [comment]
@pfulop can you provide a reproduction or some code for me to look at?

**Comment by BLamy** [comment]
Example:

Assuming `SomeContainer` and `AnotherContainer` are containers boostrapped with apollo querries using poll Interval


```js
const applications = [
  (() => {
    const title = 'SomeContainer';
    const path = '/somepath';
    const template = () => (
        <SomeApolloContainer title={title} />
    );
    return { title, path, template };
  })(),
  (() => {
    const title = 'AnotherContainer';
    const path = '/anotherpath';
    const template = () => (
        <AnotherApolloContainer title={title} />
    );
    return { title, path, template };
  })()
];

const AppWrapper = ({ children }) => (
  <div>
    {children}
  </div>
);
AppWrapper.propTypes = {
  children: React.PropTypes.object.isRequired
};

const Home = ({ applications }) => (
   <div>
   {applications.map(app => (
      <Link to={app.path} >{app.title}</Link>
  )}
  </div>
);
Home.propTypes = {
  children: React.PropTypes.array.isRequired
};

const App = () => (
  <ApolloProvider client={client} store={store}>
      <Router history={hashHistory}>
        <Route path="/" component={AppWrapper}>
          <IndexRoute component={() => <Home applications={applications} />} />
          {
            applications.map(app =>
              <Route key={app.title} path={app.path} component={app.template} />
            )
          }
          <Route path="*" component={() => <div>404</div>} />
        </Route>
      </Router>
  </ApolloProvider>
);

export default App;
````

**Comment by pfulop** [comment]
I dig around a little and I think it may be problem with apollo-client scheduler.

The thing is, if you add something on scheduler it's nice and warm there. When you take it out, scheduler clears it's own interval function (what is expected). However if you add it back, the scheduler takes this conditions
`       if (this.intervalQueries.hasOwnProperty(interval.toString())) {
            this.intervalQueries[interval].push(queryId);
        }
`
which will say yes there is already property with this key. In this case the interval is not set again and refetch won't happen ever again... Which is worse, when you have multiple pooling intervals across the app, once this happens you can add any more to the scheduler it will just ignore it, since it will go trough the same condition and never restarts interval function.

**Comment by pfulop** [comment]
I submitted PR there so this can be probably closed.
