### ISSUE TITLE
Context updates are not propagated to child components

### ISSUE THREAD

**Issue by danielbuechele** [apollostack/react-apollo#156]
When using the `graphql` HOC, context updates are not propagated to child components. This is because if any intermediate parent returns `false` on `shouldComponentUpdate` the context is not updated. (see [react docs on context](https://facebook.github.io/react/docs/context.html#known-limitations)).
I think this is the corresponding line: https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L293
Can we check here for context changes and then return true?

**Comment by jbaxleyiii** [comment]
@danielbuechele you bet! Would you be able to write up a failing test case?

(adding a link to the issue to raise our hands of wanting a robust solution)
https://github.com/facebook/react/issues/2517

**Comment by jbaxleyiii** [comment]
Fixed in the next release! https://github.com/apollostack/react-apollo/pull/162

**Comment by nss213** [comment]
With the fix in #162 it seems like `shouldComponentUpdate` will always return true as `nextContext` is always defined -- the GraqhQL HOC itself requires context. Is there a circumstance where `nextContext` is not defined?
