### ISSUE TITLE
[API discussion] The new API does not correspond to apollo-client

### ISSUE THREAD

**Issue by rricard** [apollostack/react-apollo#163]
Hi! I'm trying to migrate to your new API and one point makes it very hard for us to migrate without making things too difficult.

Until now, we were strongly based on the way the apollo-client was modeling query options, meaning something like this:

```js
{
  query: gql`...`,
  fragments: [...frag1, ...frag2],
  variables: { ... }
}
```

For instance, we use this representation to create functions that returns these kind of structures.

This works still well while using the vanilla apollo-client but is a pain when used with react-apollo with the new API.

I would make the effort to change my whole structure if only there was a good way to use fragments easily in this setting, but there is not!

To make things clear, here is the issue I currently have, this API is not good as it is (I don't mean it's bad, there is a lot of cool stuff in there but unfortunately it is problematic according to how apollo-client modelizes things):

```
graphql(doc: Document, settings: {options: QueryOptions, ...})
```

I'll make three proposals in the next comments and I'll be able to implement the one that you prefer:

**Comment by rricard** [comment]
## Proposal 1
### Make the const query optional, read directly the query options

```
graphql(docOrSettings: Document|Settings, settings?: Settings)
```

That way, we can enable doing things like in apollo client:

```js
graphql({
  options: (ownProps) => ({
    query: gql`...`,
    fragments: [...frag1, ...frag2],
    variables: { ... }
  })
})(Comp);
```

**Comment by rricard** [comment]
## Proposal 2
### Make it easier to add const fragments

I propose this API that does not completely fix the problem but makes the fragments more accessible:

```
graphql(doc: Document, fragmentsOrSettings?: [Fragment]|Settings, settings?: Settings)
```

**Comment by rricard** [comment]
## Proposal 3
### All-in-one API

This one enables everything: better fragment access + options but it may be messy:

```
graphql(docOrSettings: Document|Settings, fragmentsOrSettings?: [Fragment]|Settings, settings?: Settings)
```

**Comment by jbaxleyiii** [comment]
@rricard I'm a little confused? why can't you do this:

```js
graphql(doc: Document, { options: { fragments: [Fragment] } })

// or
graphql(doc: Document, { options: (props) => ({ fragments: [Fragment] } }))
```

**Comment by rricard** [comment]
I can do this, yes, it just semantically separates the query. Secondly, my main issue is mainly to get Proposal 1 if possible, because I would like to still stay close to what the Apollo client would do and especially how I would use that

For example:

```js
function createSomeQuery() {
  return {
    query: gql`...`,
    ...
  };
}

graphql({options: () => createSomeQuery()})(Comp);
```

Not saying the API is bad again, but it surely could be better if we want to handle those cases.

**Comment by stubailo** [comment]
I think it's a pretty good point actually, that you can't create functions that generate the options.

Is a wrapper like the below basically what you are thinking about? Or is there something more complicated? (not saying that's a good solution, just trying to get an idea about your needs)

```js
function myContainer(options, props) {
  return graphql(options.query, { options, props });
}
```

**Comment by rricard** [comment]
@stubailo I agree it's a good point but we needed to generate queries dynamically as an escape hatch, again, not saying it's good but in our case, it was needed. I'm progressively replacing that using skip and include directives but this effectively slows down the migration ... And some new features permitted by this new API are something we really need to ;) !

**Comment by rricard** [comment]
However, your wrapper seems good indeed, problem is, we still can't dispatch dynamically queries depending on ownProps (bad, I know)

**Comment by rricard** [comment]
The main issue that I have today with the new API (mainly not well explained) is that it diverges from what the apollo client does. Having the two corresponding was really powerful and if we could bring back that in one form, I think it would enable more flexibility.

**Comment by stubailo** [comment]
@rricard oh, when I said "good point" I was talking about your original thing.

> can't dispatch dynamically queries depending on ownProps

Good point as well. Hmm... yeah I think your proposal will solve it, by having one big options thunk, but I wonder if having too many ways to do stuff will be bad. I'd also like to see what @tmeasday thinks about it.

> Having the two corresponding was really powerful

Did you end up using both APIs together? And sharing the options between them?

**Comment by rricard** [comment]
Yes, as we have a legacy (backbone) and a new (react) env cohabiting, we use both API. We even use those query generation functions in both backbone and react (we share it via a global var, but since we want to nuke backbone ASAP, that's good enough!)

**Comment by jbaxleyiii** [comment]
@rricard one of the things that I added as an escape hatch is the [`withApollo`](http://docs.apollostack.com/apollo-client/react.html#withApollo) HOC. For cases when you need to do dynamic queries.

I also added a `skip: true` so you could define the queries but not run them http://docs.apollostack.com/apollo-client/react.html#graphql-options

**Comment by rricard** [comment]
withApollo doesn't give the whole react-apollo experience unfortunately, but I agree, if I really get stuck I'll fallback on that! 😉

**Comment by rricard** [comment]
anyway, I understand the issue with implementing this proposal and definitely, we'll do what works best! In the meantime, I'll try anyway to shape things the way it should be: the new API

**Comment by jbaxleyiii** [comment]
So just so I understand, everything can be done with the current API except dynamically creating the operation?

**Comment by stubailo** [comment]
That, and you need a custom wrapper to be able to share the options object.

**Comment by rricard** [comment]
@stubailo the custom wrapper is not that bad, I should have thought about it.

**Comment by rricard** [comment]
Last thing are the fragments but I suggest we should move the discussion elsewhere... Let's handle the dynamism first!

**Comment by rricard** [comment]
@jbaxleyiii Just got how skip would work for dynamic queries! Indeed there is no need to change the API **but** having Proposal 1 would still help keeping things concise I think. I mean it's up to you but if it's not that hard to implement I think it's worth a shot.

**Comment by jbaxleyiii** [comment]
@rricard 🎉 so glad!

Sadly most of the current API is built around the idea of a static query which makes changing to be dynamic would very difficult.

I do want to make sure we make all needs possible!

**Comment by tmeasday** [comment]
Given that dynamic queries seem to be discouraged by GraphQL (and us?), I think it's OK that using them is a bit less nice.

@jbaxleyiii I definitely see why it's a problem with the current implementation to consider the above APIs. Perhaps after we implement https://github.com/apollostack/apollo-client/issues/554 it might become easier. Not sure it will though :)

**Comment by stubailo** [comment]
I think we aren't talking about totally dynamic queries - it's more like "if this prop, pass query A, if this other prop, pass query B".

**Comment by jbaxleyiii** [comment]
@stubailo yeah I get that. fwiw I do think the `skip: boolean` solves that pretty well

**Comment by jbaxleyiii** [comment]
closing for now, if we want to keep discussing feel free to open

**Comment by rricard** [comment]
@jbaxleyiii I'll try to see if Proposal 1 is doable and in this case submit a PR. Are you ok with this design ? (I don't want to work on something that will be abandoned later...)
