### ISSUE TITLE
Getting "Variable was not provided" but variable is there

### ISSUE THREAD

**Issue by olistic** [apollostack/react-apollo#164]
Hey! I'm decorating a component using `graphql` and I'm getting the following error:

> Variable "$token" of required type "String!" was not provided.

However, the variable `token` is being provided (I can also see it's there by inspecting the `APOLLO_QUERY_INIT` action).

```javascript
// MyComponent.jsx

const GET_PROFILES = gql`
  query getProfiles($token: String!) {
    player(token: $token) {
      profiles {
        id
      }
    }
  }
`;

const withData = graphql(GET_PROFILES, {
  options() {
    return {
      variables: {
        token: 'shhhhhhh',
      },
    };
  },
});

export default withData(MyComponent);
```

Am I doing anything wrong?

**Comment by olistic** [comment]
I figured it out, it was a problem with my server implementation actually (I'm not using apollo-server). I thought variables were merged into the query string in the client, while they are sent along with the query in the request and need to be handled by the server.

Passing the `variables` body param to the [graphql](http://graphql.org/docs/api-reference-graphql/#graphql) function solved it.

**Comment by hems** [comment]
@olistic jeezzz, thanks for that! i was killing myself changing my frontend code just to find out i also wasn't sending variables along on the server!

**Comment by lechneal** [comment]
@olistic omg, thanks so much! I was also stuck for hours. I'm using apollo-client and graphql-tools to mock the data. 
Passing the request variables to the graphql function worked like a charm:
graphql(executableSchema, request.query, null, null, request.variables)

**Comment by galileomd** [comment]
@olistic wait could you spell out how the function writeup would look?
'''
const GET_PROFILES = gql`
  query getProfiles($token: String!) {
    player(token: $token) {
      profiles {
        id
      }
    }
  }
`;

const withData = graphql(GET_PROFILES, {
  options() {
    return {
      variables: {
        token: 'shhhhhhh',
      },
    };
  },
*** how do variables get inserted here ? ***
});

export default withData(MyComponent);

**Comment by mridulsri** [comment]
Thanks, @galileomd, and @olistic   you approach solved my issue.

**Comment by polson** [comment]
I can't believe this isn't part of the documentation...
