### ISSUE TITLE
ChildContext of component inside render function seems not detected in SSR in v0.4.7

### ISSUE THREAD

**Issue by raymondsze** [apollostack/react-apollo#166]
I am using react-apollo with material-ui.

in server side
```
<ApolloProvider store={store} client={client}>
 <App>
   <RouterContext {...renderProps} />
 </App>
</ApolloProvider>
```

here is render function inside App

App.render
```
<div>
  <MuiThemeProvider>
     {children}
  </MuiThemeProvider>
</div>
```
content of MuiThemeProvider: https://github.com/callemall/material-ui/blob/0.15-stable/src/styles/MuiThemeProvider.js

get this error: `TypeError: Cannot read property 'prepareStyles' of undefined`

However, I changed to this, it would works.
```
class App extends React.Component {
  static propTypes = {
    children: PropTypes.node.isRequired,
  };
  static childContextTypes = {
    muiTheme: PropTypes.object.isRequired,
  };
  getChildContext() {
    return {
      muiTheme: getMuiTheme(null, { userAgent: 'all' }),
    };
  }
  render() {
    const { children } = this.props;
    return (
      <div>
        {children}
      </div>
    );
  }
}
```
So what I think is the child context specified in component inside render function cannot pass down to  its children components.

**Comment by jbaxleyiii** [comment]
@raymondsze would you be able to create a failing test for this? I'm not sure I'm following 100%

**Comment by jbaxleyiii** [comment]
in the next release (going out now!)
