### ISSUE TITLE
react-apollo setup - "Cannot read property 'getState' of undefined"

### ISSUE THREAD

**Issue by Ice32** [apollostack/react-apollo#171]
I'm new to Apollo, but I'm having some real problems connecting it to react/redux. I keep on getting "Cannot read property 'getState' of undefined" error on page load even though my createStore returns a valid redux store and you can call its getState method. The weird part is, **if I call a simple query (any query, I guess) in my index.js file before anything else, I don't get this error**. Here's my setup:

index.js
```
const query = gql`{posts{title}}`;
//uncommenting this query makes everything work fine
/*client.query({query})
    .then(data => {
        console.log(data);
    });*/
let store = configureStore();
render(
    <ApolloProvider store={store} client={client}>
            <App/>
    </ApolloProvider>,
    document.getElementById("root"));
```
configureStore.js
```
export function configureStore(initialState) {
    const enhancers = compose( applyMiddleware(client.middleware()), window.devToolsExtension ? window.devToolsExtension() : f => f);
    return createStore(rootReducer,initialState, enhancers);
}
```

rootReducer.js
```
export default combineReducers({
    test,
    apollo:client.reducer()
});
```
my component
```
const mapStateToProps = (state, ownProps) => {
    console.log("state in mapStateToProps", state);
    return{
        state: state
    };
};
const postsQuery =gql`{posts{title, author, content, _id}}`;
PostsList = connect(mapStateToProps)(PostsList);
export default graphql(postsQuery)(PostsList);
```

browser console:
![console](https://cloud.githubusercontent.com/assets/10289395/17983327/4d62e39e-6b0c-11e6-993c-5cc7b962e06a.PNG)

**Comment by Ice32** [comment]
It seems that this fix from another issue also fixes my problem:
https://github.com/apollostack/react-apollo/compare/master...msimulcik:master

**Comment by jbaxleyiii** [comment]
@Ice32 this looks like an issue with a missing store? Do you have a reproduction repo I can use to debug?

**Comment by Ice32** [comment]
@jbaxleyiii Here it is:
https://github.com/Ice32/react-apollo-bug-reproduction

Here's the component in which I'm connecting to Apollo:
https://github.com/Ice32/react-apollo-bug-reproduction/blob/master/src/js/components/postsList/PostsList.js

BTW, any critique on my code/app structure is very welcome (I'm not asking you to analyze my code, but if you notice something bad, I'd be more than glad to hear it).

**Comment by jbaxleyiii** [comment]
@Ice32 The issue with the setup you have is you are creating multiple clients.

1. https://github.com/Ice32/react-apollo-bug-reproduction/blob/master/src/js/main.js#L18
2. https://github.com/Ice32/react-apollo-bug-reproduction/blob/master/src/js/store/configureStore.js#L34
3. https://github.com/Ice32/react-apollo-bug-reproduction/blob/master/src/js/reducers/rootReducer.js#L8

The client should only be created once then passed to these other files (or create the store in one file

**Comment by drFabio** [comment]
I have only a Client and I put only the apollo reducer  just using
```javascript
const reducer =  combineReducers({
    apollo: client.reducer()
  })
```
And I am also receiving 

> Caught an exception! TypeError: Cannot read property 'getState' of undefined

Is there something else to connect redux ?

**Comment by drFabio** [comment]
Just doing
```javascript
const store = createStore(client.reducer())
```
```html`
  <ApolloProvider client={client} store={store}>

````
Also is not working for the time

**Comment by drFabio** [comment]
I had to do:
```javascript
const createStoreWithMiddleware = applyMiddleware(client.middleware())(applyMiddleware(thunk)(createStore))
const store = createStoreWithMiddleware(getReducer(client.reducer()))
```
