### ISSUE TITLE
Avoid importing from sub-directories of apollo client

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-apollo#172]
Hey, right now it's pretty hard to use react-apollo or apollo-client with `npm link` because this package reaches into sub-directories of the published package.

I'd love to be able to eliminate that completely.

Can we just make a list of everything that needs to be exported from `apollo-client` to avoid the internal imports?

**Comment by jbaxleyiii** [comment]
sure thing! I'll open a PR to the client with all of the needs. It's mostly type defs anyway

**Comment by jbaxleyiii** [comment]
@stubailo after the next AC release, I can change this around!
