### ISSUE TITLE
GraphQL variables have wrong format in query

### ISSUE THREAD

**Issue by schlaup** [apollostack/react-apollo#180]
See GraphQLHub:

[GraphQL Tour: Variables](https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56)

> How do we set the values for variables? The GraphQL spec doesn’t impose any constraints, similar to how it does not specify the mechanics of GraphQL requests in general. The GraphQL-JS ecosystem generally uses a separate JSON blob

Following Apollo's documentation and using:

```
const withUserFromId = graphql(GET_USER_WITH_ID, {
  options: (ownProps) => ({ variables: { id: ownProps.userId } })
});
const MyComponentWithData = withUserFromId(MyComponent);
```

The query should be:

`{"query":"query getUser(id: $ID!) { user { name } }\n}\n","variables":"{\n  \"id\": \"1\"\n}","operationName":"getUser"}`

but it is:

`{"query":"query getUser(id: $ID!) { user { name } }\n}\n","variables":{"id":"1"},"operationName":"getUser"}`

The value of "variables" is not in quotes as it should be. It is JSON and not a JSON blob.

Therefore the GraphQL server that I am using does not find the variables when executing the query.

**Comment by schlaup** [comment]
I investigated more and it seems that the issue is with the Apollo Client and not only with React Apollo:

[Apollo Client issue](https://github.com/apollostack/apollo-client/issues/600)

**Comment by stubailo** [comment]
Let's close this one in favor of the other
