### ISSUE TITLE
Check for client comes too late

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#183]
This line https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L262 is kind of redundant right now because it will have already errored on the line before.

@jbaxleyiii should I just fix this on devel?

While we are on the subject is it odd that we preference `props.client` to `context.client`? It's a bit of a gotcha that people can't use a prop to their component called `client`, and I'm not sure it's documented anywhere.

**Comment by jbaxleyiii** [comment]
@tmeasday thats a great point on both regards! Let's remove the prop usage and fix the warning!

**Comment by jbaxleyiii** [comment]
Fixed in next release!
