### ISSUE TITLE
updateQueries with null previousQueryResult

### ISSUE THREAD

**Issue by townmulti** [apollostack/react-apollo#186]
I get this error when I do a mutation insert that would be the first result of the query.

`Uncaught Error: Can't find field _id on result object $ROOT_QUERY.allTaskList({"userId":"q32a73EhE2SGWMHR4"}). `

I believe it is due to `previousQueryResult` being null or empty, meaning when the query was performed it returned nothing or a blank result. So the mutation is the very first insert, so when it goes to updateQueries the mutated result can't find the new` _id` to perform the update.

When my `previousQueryResult` has some actual results the error doesn't happen.

This is my query:

```
  query allTaskList($userId: String!) {
    allTaskList(userId: $userId) {
      _id
      taskDescription
    }
  }
```
This is my mutation:

```
  mutation insertTask($taskOwner: String!) {
    insertTask(taskOwner: $taskOwner) {
      _id 
      taskDescription 
    }
  }
```
This is my udateQueries on the mutation:

```
        updateQueries: {
          allTaskList: (previousQueryResult, { mutationResult, queryVariables }) => {
            if (queryVariables.userId !== ownProps.params.userId) {
              return previousQueryResult;
            }
            const originalList = previousQueryResult.allTaskList;
            const mutatedList = [];
            mutatedList.push(mutationResult.data.insertTask);
            return {
              allTaskList: merge(originalList, mutatedList)
            };
          }
```

Is this a bug, or is there a way I should be updating when my original query result is null?

**Comment by stubailo** [comment]
Curious for more info - how is the query result null? Is it when your fetch isn't done yet and you do a mutation? Or you are creating a query that isn't meant to be fetched?

**Comment by townmulti** [comment]
Sorry for the bother, looks like it was a mistake on my part, coding in circles. Originally it comes in as `this.props.data.allTaskList: Array[0]`

My testing senario was adding and removing tasks with only one in the list.

In my `removeTask` mutation I have an `updateQueries`, I mistakenly set `mutatedList` to `null` instead of `[]` as in this snippet 
```
            const originalList = previousQueryResult.allTaskList;
            let mutatedList = originalList.filter(function(item) { 
                                return item._id !== mutationResult.data.removeTask._id; 
                              }); 
            mutatedList = mutatedList.length === 0 ? null : mutatedList;
            return {
              allTaskList: mutatedList
            };
```

I had to check if the `mutatedList` was empty after the filter. I changed the `null` to `[]` and it looks to be working correctly now. 
Thanks for the inquisition! 

It brings a question to mind, is there a better way I should be comparing the objects here? The `_id` could possibly be in the middle of the list. I know if the list gets long the filter could take some time.

**Comment by stubailo** [comment]
That's pretty much how I would do it.

> mutatedList = mutatedList.length === 0 ? [] : mutatedList;

Isn't this exactly the same as `mutatedList = mutatedList`? Not sure why the conditional is necessary here.

> I know if the list gets long the filter could take some time.

I feel like if you're at the point where iterating over a list takes too long, you are probably loading too much data for the client anyway. Iterating is pretty fast.

**Comment by townmulti** [comment]
Very insightful! I appreciate your help 💯

**Comment by stubailo** [comment]
No problem!
