### ISSUE TITLE
Make `this` inside `props` and `options` the component instance?

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#188]
It seems like it's a sensible place to store state (at the moment it's undefined):

```js
const FeedWithData = graphql(FEED_QUERY, {
  props({ data: { loading, feed, currentUser, cursor, fetchMore } }) {
    return {
      loading,
      feed,
      currentUser,
      loadMoreEntries: () => {
        return fetchMore({
          query: moreComments,
          variables: {
            // cursor is the initial cursor returned by the original query
            // this.cursor is the cursor that we update via `updateQuery` below
            cursor: this.cursor || cursor,
          },
          updateQuery: (previousResult, { fetchMoreResult, queryVariables }) => {
            const previousEntry = previousResult.entry;
            const newComments = fetchMoreResult.data.comments.nextComments;

            // update internal reference to cursor
            this.cursor = fetchMoreResult.data.cursor;

            return {
              title: previousEntry.title,
              author: previousEntry.author,
              // put promoted comments in front
              comments: [...newComments, ...previousEntry.comments],
            };
          },
        });
      },
    };
  },
})(Feed);
```

Or does this seem like an antipattern? Where is a sensible spot to store `cursor` if not?

**Comment by stubailo** [comment]
I don't think we should use 'this' if we can avoid it. Given that some people like to use arrow functions all the time, etc.

**Comment by tmeasday** [comment]
@stubailo, I'm inclined to agree. But I need some "instance" to store the cursor on. The current approach (http://dev.apollodata.com/react/pagination.html#cursor-pages) is pretty crappy IMO

**Comment by tmeasday** [comment]
The only way I can really see it working is to use *another* wrapper component for "state", which is... kind of ugly.

**Comment by stubailo** [comment]
Maybe expose "setState" or something?

**Comment by tmeasday** [comment]
Or maybe just `component` as a named argument?

**Comment by jbaxleyiii** [comment]
@tmeasday would the only use case for this to update potential variables?

**Comment by tmeasday** [comment]
@jbaxleyiii I suppose so, yeah. Actually I was just thinking about it a little more -- we are just trying to get the result of our query (the `cursor` field). So maybe it's just:

```js
const FeedWithData = graphql(FEED_QUERY, {
  props({ data: { loading, feed, currentUser, cursor, fetchMore } }) {
    return {
      loading,
      feed,
      currentUser,
      loadMoreEntries: () => {
        return fetchMore({
          query: moreComments,
          variables: {
            cursor: cursor,
          },
          updateQuery: (previousResult, { fetchMoreResult, queryVariables }) => {
            const previousEntry = previousResult.entry;
            const newComments = fetchMoreResult.data.comments.nextComments;

            return {
              // by passing cursor in here, `props` will be re-run, rebinding `updateQuery` with a new cursor
              cursor: fetchMoreResult.data.cursor,
              title: previousEntry.title,
              author: previousEntry.author,
              // put promoted comments in front
              comments: [...newComments, ...previousEntry.comments],
            };
          },
        });
      },
    };
  },
})(Feed);
```

**Comment by tmeasday** [comment]
(What were you thinking?)

**Comment by jbaxleyiii** [comment]
@tmeasday I was thinking about adding a setVariables or setOptions method but because of the mixed method / object, I don't think that is practical / clear.

If what you included works. I'd say lets go that route!

**Comment by tmeasday** [comment]
Yeah, I think it works; in fact it's conceptually the same as the [previous example](http://dev.apollodata.com/react/pagination.html#numbered-pages) where we use the query results (`feed.length`) to bind the `loadMoreEntries` function w/ the correct `offset`.

I should dip my toes in and try and create a test case for this maybe?

**Comment by tmeasday** [comment]
Closing this and I'll update the guide example.

**Comment by jbaxleyiii** [comment]
@tmeasday that would be an awesome test case!
