### ISSUE TITLE
Allow using data from queries in mutations in the same container

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-apollo#19]

**Comment by jbaxleyiii** [comment]
@stubailo can you give me an example? Like fetch from the query to pass data to the mutation?

**Comment by jbaxleyiii** [comment]
Fwiw, when calling a mutation to take place, you can define all the args you want so you could pass data from a query to the mutation

**Comment by stubailo** [comment]
Ah, I forgot mutations take arguments! Yeah, I guess I can just pass the data from the props back up, no big deal!

**Comment by linonetwo** [comment]
Seems I can 't use mutation and query in the same component? Using two mutations in a component seems unsupported too. @stubailo

**Comment by linonetwo** [comment]
Solved, by looking at https://github.com/apollostack/react-apollo/issues/238
