### ISSUE TITLE
withApollo missing from docs

### ISSUE THREAD

**Issue by stretchkennedy** [apollostack/react-apollo#195]
`withApollo` seems to be missing from the new documentation. I had to go digging in Google's cache of the old page to find it.

**Comment by jbaxleyiii** [comment]
@tmeasday is this something you can help out with? I need to get the new docs running on my system

**Comment by tmeasday** [comment]
It's here: http://dev.apollodata.com/react/initialization.html#withApollo do you guys think it should be somewhere else?

**Comment by jbaxleyiii** [comment]
@tmeasday oh that looks like a great spot! Thanks!

**Comment by stretchkennedy** [comment]
Huh. I started looking in the usage section, and must have missed it when scanning through initialisation. My bad. 

I don't have a problem with its current location. Once google picks up the new docs, everything should be fine, so I'm closing the issue.

**Comment by pbrink231** [comment]
Does this not exist anymore?  There is nothing in the documentation that was linked by @tmeasday

**Comment by bxt** [comment]
I think the docs for `withApollo` can now be found here: https://github.com/apollographql/react-docs/blob/master/source/api.md#withApollo

**Comment by ujwal-setlur** [comment]
@bxt that link goes nowhere.

**Comment by bxt** [comment]
@ujwal-setlur It seems the whole repo was removed. The docs can now be found here: https://www.apollographql.com/docs/react/api/react-apollo.html#withApollo

**Comment by vipulgupta2048** [comment]
Hi, is it just me or I think there should be more documentation on how to perform mutations while using withApollo. That 10-15 lines just doesn't cut it. Any examples would also help, if someone could point me to them.

**Comment by ujwal-setlur** [comment]
I completely agree. I use withApollo and it works great, but it suspiciously feels like a bastard step-function...

**Comment by vipulgupta2048** [comment]
Hey @ujwal-setlur Can you post maybe a gist for the example maybe or some form of documentation, or even a blog post on it ?

**Comment by ujwal-setlur** [comment]
Yes i will in just a bit
