### ISSUE TITLE
mapStateToProps params

### ISSUE THREAD

**Issue by johnthepink** [apollostack/react-apollo#20]
It looks like `mapStateToProps` currently gets called with just the redux state. The docs show that it gets called with an object containing `ownProps` and `state`. Is it intended to contain `ownProps` as well? Or should we update the docs? cc @jbaxleyiii

**Comment by jbaxleyiii** [comment]
@johnthepink it should have ownProps. I thought I had a test in place for that?

**Comment by stubailo** [comment]
I had a few issues with various arguments as well. I don't think our tests totally cover the different lifecycle events with changes coming from props, redux, etc.

**Comment by jbaxleyiii** [comment]
@stubailo the tests are pretty minimal right now. @johnthepink would you be up go taking that for me today and tomorrow? Trying to be better about actually being on vacation ;)

**Comment by stubailo** [comment]
I managed to build an example app on top of it, so I'm happy! No rush on making these improvements, I think - vacation away!

**Comment by jbaxleyiii** [comment]
@stubailo @johnthepink is triumphantly moving our stavj to Apollo now so he may need some changes.

I'm really happy it's all decent ly coming together though!

**Comment by johnthepink** [comment]
Yep! I'll jump in on fixing some stuff here soon. Found a couple other things.

**Comment by jbaxleyiii** [comment]
Fixed with #51
