### ISSUE TITLE
mapQueriesToProps state

### ISSUE THREAD

**Issue by johnthepink** [apollostack/react-apollo#21]
In my current implementation, `mapQueriesToState` gets called the first time with `ownProps` and `state` in the object correctly. However, when the store is updated, and the function is called a second time (and each subsequent time), `state` isn't the redux store state. Instead, it's an object containing the ApolloClient instance, and the store instance: 

```json
{
  "ownProps": { // correct },
  "state": {
    "client": { //ApolloClient },
    "store": { //ApolloStore }
  }
}
```

**Comment by stubailo** [comment]
@johnthepink update the package? I just fixed this I think: https://github.com/apollostack/react-apollo/commit/cf5e5b68d8df4989228b96ec6755e422e803912b

**Comment by johnthepink** [comment]
@stubailo updated and it looks like it's still doing it for me. i'll debug some more

**Comment by johnthepink** [comment]
nope. you were right. i had a stray dependency
