### ISSUE TITLE
Strategy for not catching errors?

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-apollo#214]
https://twitter.com/dan_abramov/status/776891811222675457

**Comment by jbaxleyiii** [comment]
@stubailo currently we only catch ApolloError's thrown within the observable and pass all the rest as typical throws.

https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L522-L525

Are you seeing error issues?

**Comment by stubailo** [comment]
Oh ok never mind - I'm way behind.
