### ISSUE TITLE
this.props.data without query root field

### ISSUE THREAD

**Issue by tommyJS** [apollostack/react-apollo#216]
I would like to ask if do something wrong. I have the following React Component:
```js
import React from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import { connect } from 'react-redux';

import s from './menu.scss';

class Menu extends React.Component {

  render() {
    console.log(this.props);

    const { wp_query } = this.props.data;

    return (...);
  }
}

const getMenu = gql`
  query getMenu {
    wp_query {
      menu (name: "pl") {
        id
        title
      }
    }
  }
`;

const MenuWithData = graphql(getMenu)(Menu);

export default MenuWithData;
```

`console.log` returns:
```
{ data: 
   { loading: true,
     errors: null,
     variables: undefined,
     refetch: [Function],
     fetchMore: [Function],
     updateQuery: [Function] } }

```

Unfortunately, there is no query root field: `wp_query`.
What might be wrong?
In advance, thank you for resolving this issue. I used the [official documentation](http://dev.apollodata.com/react/queries.html#basics).

**Comment by stubailo** [comment]
It is currently loading, since `loading: true` is set. Have you tried waiting for loading to complete?

**Comment by tommyJS** [comment]
Thank you for the fast reaction. I got the point.
I use `menu.map` in `return (...)`, so the app was just crashing and the component never rendered correctly.

Now, I do something like this:
```js
    const { loading } = this.props.data;

    if (loading) {
      return (<div>loading...</div>);
    }

    const { wp_query } = this.props.data;
    const { menu } = wp_query;
```
and it works. However, I have a question: do I need to always check loading flag or is there any option to render only when loading equals false?

**Comment by jbaxleyiii** [comment]
@tommyJS there currently isn't although I've thought about that as an option

**Comment by tommyJS** [comment]
Thank you for the answers. Feel free to reopen.

**Comment by linonetwo** [comment]
@ghost Seems any failure inside Component will cause graphql to stop loading, and 'loading' kept in true. Do your agree?
