### ISSUE TITLE
Use "reduxRootSelector" client's property instead of deprecated "reduxRootKey"

### ISSUE THREAD

**Issue by wizardzloy** [apollostack/react-apollo#220]
The API of the client changed [here](https://github.com/apollostack/apollo-client/pull/662) so we need to use the new constructor parameter `reduxRootSelector` instead of the deprecated `reduxRootKey`

**Comment by stubailo** [comment]
Duplicate: https://github.com/apollostack/react-apollo/issues/209

Also, this makes me think we should add back `reduxRootKey` for backcompat if we don't want to bump the minor version (and we don't) since who knows what could be using it.

**Comment by wizardzloy** [comment]
@stubailo should I make the change or you'll handle that?

**Comment by stubailo** [comment]
I wasn't planning on it - I'd say open a PR for sure

**Comment by wizardzloy** [comment]
ok
