### ISSUE TITLE
Data not added after insert mutation to Relay compliant GraphQL server

### ISSUE THREAD

**Issue by ivosabev** [apollostack/react-apollo#227]
I have a GraphQL server that is compliant with the Relay specification and a React/Redux client.

I do a query and it returns the data as expected:
```
query Teams {
  teams: teamNodes {
    nodes {
      id,
      name
    }
  }
}
```

Then I call my insert mutation:
```
insertTeam(input: $input) {
  team {
    id,
    name
  }
}
```

I see the new record being added to the `apollo.data` store, but the entry doesn't show in my list of entries.

Update mutations work just fine.

I believe it is something with the __typename as the Relay result is of type TeamConnection and inside are the nodes of type Team, but I am not sure how to handle this on the Apollo side. 

Any ideas? Thanks!

**Comment by stubailo** [comment]
How did your mutation look when using Relay? (If you were using Relay before)

**Comment by ivosabev** [comment]
I haven't got a Relay client side, but as I said the mutation works in Apollo and its result gets inserted into the `apollo.data` store, but the UI where I show my query doesn't get updated.

The mutation code is:
```
mutation insertTeam($input: InsertTeamInput!) {
  insertTeam(input: $input) {
    team {
      id,
      name
    }
  }
}
```

I suspect after the insert mutation the `id` should be appended to the `$ROOT_QUERY.teamNodes.nodes`, but I doesn't.

**Comment by stubailo** [comment]
Yeah there is no way to automatically insert items into arrays with GraphQL - having a relay-compatible mutation doesn't really help.

Have you looked into the "updateQueries" option to mutations which let you update query results? It's designed for this situation.

**Comment by jbaxleyiii** [comment]
Closing due to lack of response
