### ISSUE TITLE
Sometimes return null for non-null type

### ISSUE THREAD

**Issue by linonetwo** [apollostack/react-apollo#230]
When data is still loading, data that I want will be undefined, So I use:

``` javascript
const queryConfig = {
  props: ({ ownProps, data: { refetch, loading, Config = {}, LineChart, LineChartSources, error } }) => ({
    refetch,
    loading,
    error,
    indicatorTypes: Config.indicatorTypes,
    LineChart,
    LineChartSources, // this is [String]!
  })
};

......

  static propTypes = {
    indicatorTypes: PropTypes.array.isRequired,
    LineChart: PropTypes.array.isRequired,
    LineChartSources: PropTypes.array.isRequired,
  }

  static defaultProps = {
    indicatorTypes: [],
    LineChart: [],
    LineChartSources: [],
  }
```

to avoid empty data passing to UI logic, such as Array.map() .

But sometimes, LineChartSources will still become null, causing enigmatic error: `typeerror no default value` and props validation error: `invalid prop of type object supplied to LineChartSources, expect array`

I guess that it's similar to https://github.com/apollostack/apollo-client/issues/664 where some UI error blocks Apollo from working properly.

**Comment by tmeasday** [comment]
Is the issue here that `defaultProps` doesn't work when the field is set to `null`?

I think you are better just writing something like:

```js
const queryConfig = {
  props: ({ ownProps, data: { refetch, loading, Config = {}, LineChart, LineChartSources, error } }) => {
    if (loading) {
      return {
          loading: true,
      };
    } else {
      return {
        refetch,
        loading,
        error,
        indicatorTypes: Config.indicatorTypes,
        LineChart,
        LineChartSources, // this is [String]!
      };
    }
  })
};
```

**Comment by tmeasday** [comment]
(closing because I don't think it's an issue with RA per se).

**Comment by linonetwo** [comment]
Thanks for reply, this can be added to graphql best practice or so.
