### ISSUE TITLE
Expose updateQueries for query operations and not just mutations

### ISSUE THREAD

**Issue by migueloller** [apollostack/react-apollo#233]
Sometimes, one wants to cache objects that result from some query that could also appear on the root query by id. I go into more detail on this here: apollostack/apollo-client#706.

A potential solution to this could be by passing `updateQueries` for query operations (and not just for mutation operations). This would allow the user to simply update the relevant queries given the data they get back. If they want to update the root query so that it caches an object by it's id then they can do that.

What do you guys (@helfer, @tmeasday, and @stubailo) think?

**Comment by tmeasday** [comment]
@migueloller I'm confused why we want this issue on RA as well as https://github.com/apollostack/apollo-client/issues/706? 

Ultimately, the RA will mirror AC pretty closely so let's solve the issue there first and then bring it here.

**Comment by migueloller** [comment]
@tmeasday, fair enough. I'll comment on apollostack/apollo-client#706 mentioning a variation of this as a potential solution. I didn't care to do that initially because `updateQueries` is a `react-apollo` thing (as far as I know... I might be wrong).

**Comment by tmeasday** [comment]
Oh, no `updateQueries` is definitely an `apollo-client` thing. http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.mutate

**Comment by migueloller** [comment]
@tmeasday,

I see, I apologize for the confusion. I'll mention the suggested solution in the other issue and close this one.
