### ISSUE TITLE
call refetchQueries without mutation | question

### ISSUE THREAD

**Issue by seeden** [apollostack/react-apollo#241]
Is it possible to call refetchQueries without mutation? 
Here is my scenario:
Logged user is trying to logout. That means I will just delete bearer token locally. But I need to refetch viewer from server after this operation.

something like:
```js
@graphql(gql'', { refetchQueries: ['viewer'] })
```

I tried but without any success
```js
this.context.client.mutate({ refetchQueries: ['viewer'] });
```

**Comment by stubailo** [comment]
The new Apollo Client API will have this functionality.

**Comment by seeden** [comment]
Thank you @stubailo

**Comment by jbaxleyiii** [comment]
closing since this is an AC feature
