### ISSUE TITLE
add client as optional parameter to decorator

### ISSUE THREAD

**Issue by seeden** [apollostack/react-apollo#242]
It would be nice to have ability to get apollo client via @graphql instead of using contextTypes
Here is small example

```js
@graphql(..., { 
  client: true,
})
class MyComponent extends Component {
  myFunction() {
    const { client } = this.props;
  }
}
```

I can create a PR if you agree with it

**Comment by jbaxleyiii** [comment]
@seeden have you tried out http://dev.apollodata.com/react/higher-order-components.html?

**Comment by jbaxleyiii** [comment]
Specifically the `withApollo‘?

**Comment by seeden** [comment]
thank @jbaxleyiii  withApollo is working
