### ISSUE TITLE
0.5.7 Typings break artifactory npm proxies

### ISSUE THREAD

**Issue by mmmdreg** [apollostack/react-apollo#243]
Version: react-apollo@0.5.7

In corporate environments, it is common to have internal proxies for dependency repositories for various environments (maven, npm, gem etc). 

At my current company, our internal repositories use artifactory, which does not support typings (https://www.jfrog.com/jira/plugins/servlet/mobile#issue/RTFACT-11980). This makes it impossible to use the latest react-apollo. 

apollo-client typings are in dev dependencies so no issues yet.

**Comment by jbaxleyiii** [comment]
fixed in the next release (out today)
