### ISSUE TITLE
Server Side Rendering and skip option

### ISSUE THREAD

**Issue by pfulop** [apollostack/react-apollo#244]
Hi,
 I am using skip option to get user name only if he is authenticated. However, it looks like this option is ignored by  renderToStringWithData since the query will fire anyway.
```js
const me = graphql(gql `
  query me{
    me{
      fullname
     }
}
 `,{
  options: (ownProps) => ({ skip: true })
  });
```

**Comment by jbaxleyiii** [comment]
@pfulop this is fixed with #253 which will be released today!
