### ISSUE TITLE
Feature request: Pass `skip` outside of `options` so you can assume skip is false when evaluating other options

### ISSUE THREAD

**Issue by glasser** [apollostack/react-apollo#245]
## Steps to Reproduce

A common reason that you might want to use `skip` is that some necessary data for evaluating the query is not available.  For example:

```js
const FooWithData = graphql(query, {
  options: ({foo}) => ({
    skip: !foo,
    variables: {
      bar: foo.bar
    }
  })
})(Foo);
```

### Buggy Behavior

However, you can't actually write the code as above: the `skip` and `variables` fields are evaluated at the same time, so you have to check `foo` again in the variables clause.

### Expected Behavior

I'd like to be able to instead write:

```js
const FooWithData = graphql(query, {
  skip: ({foo}) => !foo,
  options: ({foo}) => ({
    variables: {
      bar: foo.bar
    }
  })
})(Foo);
```

Then I can assume while writing the arguments to `options` that we aren't skipping the query.

### Version
- apollo-client@0.4.19
- react-apollo@0.5.7

**Comment by stubailo** [comment]
The same applies to `props` IMO, which was opened as #212 before.

**Comment by glasser** [comment]
Note that we might want to keep the old `skip` around for backwards compatibility.

**Comment by jbaxleyiii** [comment]
@glasser @stubailo well presented! I'm onboard and will do!

**Comment by stubailo** [comment]
I think @glasser is going to give it a shot!

**Comment by jbaxleyiii** [comment]
oh perfect!

A couple thoughts:
1. What happens if skip becomes true after a query is already being watched?
  - should we unsubscribe?
  - should the old props (data / etc) go away?
2. We will need to make sure this works on SSR as well

**Comment by stubailo** [comment]
I'd say yes and yes - it should be as if the component was I rendered IMO.

**Comment by glasser** [comment]
@stubailo Actually, between my trouble getting a test environment up (blocking on @tmeasday fixing a test) and my lack of familiarity with the code, I think I'm going to just work around this for now instead of fixing this.
