### ISSUE TITLE
unsubscribeQuery is not working properly

### ISSUE THREAD

**Issue by seeden** [apollostack/react-apollo#252]
## Steps to Reproduce

1. create component with graphql decorator
2. do multiple componentDidMount and componentWillUnmount (for example with react-router I have this component in my header menu)
3. after each cycle you will see more and more same queries like

```js
{
  "data": {
    "___viewer___requestIndex_0___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_1___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_2___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_3___fieldIndex_0": {
      "id": "5",
    },
    "___viewer___requestIndex_4___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_5___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_6___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_7___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_8___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_9___fieldIndex_0": {
      "id": "5"
    },
    "___viewer___requestIndex_10___fieldIndex_0": {
      "id": "5"
    },
  }
}
```

### Buggy Behavior

The number of queries is bigger and bigger. After first cycle I can see just one query. After five cycles there are 5 queries...

I am not sure but maybe there is a problem with unsubscribeQuery

### Expected Behavior

The number of queries will be same

### Version
- apollo-client@0.4.20
- react-apollo@0.5.7

**Comment by jbaxleyiii** [comment]
@seeden would you be able to help reproduce or create a failing test case? I was unable to initially reproduce it https://github.com/apollostack/react-apollo/pull/254

**Comment by jbaxleyiii** [comment]
actually, an older version of AC I have locally works, but the newer version doesn't!

**Comment by jbaxleyiii** [comment]
@stubailo this looks like a bug in AC

**Comment by jbaxleyiii** [comment]
@seeden confirmed this is a bug introduced in apollo-client 0.4.20

For now, I'm going to lock the AC version to 0.4.19 as the top range. With the upcoming refactor, some internals in react-apollo will have to change as well so it will be a minor level change in both libraries

**Comment by seeden** [comment]
Thank you @jbaxleyiii  I am going to try 0.4.19

**Comment by seeden** [comment]
@jbaxleyiii I have same problem with apollo-client 0.4.19

**Comment by tmeasday** [comment]
@seeden can you try with 0.5.9?

**Comment by seeden** [comment]
@tmeasday the problem is still here with 0.5.9. I can see this issue when I change the route in react-router but component with this query is always visible. Therefore I think that there is a problem with componentWillReceiveProps or something like that.

**Comment by tmeasday** [comment]
So AC doesn't remove the query from the store when you stop it:

https://github.com/apollostack/apollo-client/blob/master/src/queries/store.ts#L137

```js
if (isQueryStopAction(action)) {
    const newState = assign({}, previousState) as QueryStore;

    newState[action.queryId] = assign({}, previousState[action.queryId], {
      loading: false,
      stopped: true,
    }) as QueryStoreValue;

    return newState;
}
```

@seeden I'm not sure what you are showing in the first code snippet? But in any case this isn't a bug in `react-apollo`. I don't think it's really a bug in `apollo-client` as currently designed.

**Comment by tmeasday** [comment]
(By which I mean the store in AC will grow without bounds as you use it).

**Comment by stubailo** [comment]
@tmeasday that looks like a batched query, so perhaps there is something broken in there. But definitely not related to apollo client.

**Comment by tmeasday** [comment]
Ok, perhaps the bug is different from what @jbaxleyiii (and I) thought, wrt queries remaining in the store.

@stubailo do you mean definitely not related to `react-apollo`? It actually sounds like it could be a bug with query batching in AC. @seeden can you open a bug there w/ a little more info?

**Comment by stubailo** [comment]
You're right! I meant not related to react-apollo.

**Comment by seeden** [comment]
I am going to try AC@0.5 again today and I will let you know. I saw few days version from trunk and few my reported bugs were fixed already. (I will close these bugs too). Anyway you are doing a great work. Thank you

**Comment by seeden** [comment]
This problem is still here in AC@0.5 and latest react-apollo. I can see 20 same queries in one time
