### ISSUE TITLE
0.5.8 version seems to be broken, 0.5.7 is fine

### ISSUE THREAD

**Issue by vlasenko** [apollostack/react-apollo#258]
## Steps to Reproduce

1. Clone this example:
  ``` git clone https://github.com/sysgears/apollo-fullstack-starter-kit ```
2. Run the example:
  ``` npm start ```
3. Point your web browser to `http://localhost:3000` and check that there is no React warnings in the browser console
4. Modify package.json, to replace react-apollo version from `0.5.7` to `0.5.8`
5. Run ``` npm update ```
6. Stop and then start the example with ``` npm start ``` again.
7. Point your web browser to `http://localhost:3000` and check that there ARE React warnings in the browser console:

```
warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) " data-reactid="10">Loading...</div></di
 (server) " data-reactid="10"><div data-reactid="1
```

### Buggy Behavior

React warnings about markup mismatch on server and client in web browser console.

### Expected Behavior

Should be no React warnings in web browser console and the markup on server and client should match.

### Version
- apollo-client@0.5.8
- react-apollo@0.4.20

**Comment by jbaxleyiii** [comment]
@vlasenko I see the error but I'm not sure what is causing it? The server side render seems to be correct. This leads me to believe it is an issue with starting up apollo-client with the correct data store? I'll try to look into it more this week!

**Comment by vlasenko** [comment]
I'm not sure as well, but 0.5.7 and 0.5.6 of react-apollo do not trigger this problem. I will investigate on my side the coming week too and if I find some pointers I report here.

**Comment by vlasenko** [comment]
@jbaxleyiii @tmeasday The offending commit for the issue is this one:
https://github.com/apollostack/react-apollo/commit/246eca0f46e52062cf63c08074da04c42b5e57cf

Right before this commit issue doesn't get triggered. After this commit the issue shows up.

**Comment by vlasenko** [comment]
Seems in 0.5.8 on the client-side query results don't get really read from Initial Apollo Store which came from server.

**Comment by tmeasday** [comment]
The issue is that you aren't using the same apollo client options on client and server; specifically, on the client you have [a `queryTransfomer`](https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/client/main.jsx#L31) whereas on the server [you do not](https://github.com/sysgears/apollo-fullstack-starter-kit/blob/master/src/server/middleware/website.jsx#L47-L52).

This means the query isn't the same and so it cannot read the results from the store. You could use `returnPartialData` to get around this in general, but I think in this case it's just a bug.

**Comment by vlasenko** [comment]
Many thanks Tom, for tracking this down!
