### ISSUE TITLE
Refactor to calculate `this.data` at render time

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#264]
It seems like we are going through [some contortions](https://github.com/apollostack/react-apollo/pull/260#issuecomment-253064810) to keep `this.data` up to date, which seems unnecessary given we can now call `this.queryObservable.currentResult()` in the render function to get the current data.

So I would suggest something like:

``` js
render() {
  let data;
  if (/*skipping*/) {
    data = { loading: false, errors: null };
  } else {
    data = assign({}, this.queryObservable.currentResult());
    // copy fields over from queryObservable
  }

  // now render wrappedComponent with data
}
```

**Comment by jbaxleyiii** [comment]
@tmeasday YES!! I love this idea!
