### ISSUE TITLE
Plan for subscription integration for graphql() ?

### ISSUE THREAD

**Issue by saeho** [apollostack/react-apollo#266]
Is there a plan for subscription integration with react-apollo's graphql() "with Data" function? (i.e. the same way queries and mutations are mapped)

Or is the plan to stick with GitHunt demo's way of subscribing using the Apollo Client on componentDidMount?

**Comment by jbaxleyiii** [comment]
@saeho I quietly shipped it I'm 0.5.8 :). Can you give it a shot? Same usage as a query

**Comment by saeho** [comment]
@jbaxleyiii I tried it in React-Native. Pretty much the same usage as query except instead of query, "subscription".

However I'm getting a very non descriptive error that's very hard to debug.

```
err [Object]
{
message: "Cannot read property 'value' of undefined"
}
```

Hard to tell if this is an error from the server or client. But I know that I'm not trying to access the property "value" of any object in either my client or server code.

Any ideas?

**Comment by saeho** [comment]
Sorry, the error above is for something else. That was my second attempt to get subscription to work without your new feature.

Using your feature, I get:
```
[object Object]
```

I get exactly that in String format. Which is not really debuggable.

**Comment by saeho** [comment]
Versions I'm using:
```
    "apollo-client": "^0.4.20",
    "react-apollo": "^0.5.9",
    "graphql-tag": "^0.1.14",
    "subscriptions-transport-ws": "^0.2.5",
```

**Comment by saeho** [comment]
After a lot of trial and error I discovered this won't work:
```
subscription {
...
}
```

Changing it to this worked:
```
subscription testSub {
...
}
```

However, every time a publish event happens in the server, WS on the client is triggered, which is good but every WS publish event crashes with "Cannot read property 'data' of undefined".

**Comment by saeho** [comment]
@0.5.10 fixed it. Thanks!

However I noticed that the socket connection is not persistent. If I turn off the socket server and restart it, I expect the App to reconnect to the socket server. However it doesn't.

Is there an option to enable re-connect?

**Comment by saeho** [comment]
From the subscriptions-ws package, I discovered that there is a reconnect: true option!

It seems to work great! Can't wait for the official documentation. Thank you!
