### ISSUE TITLE
reduxRootSelector not found

### ISSUE THREAD

**Issue by sedubois** [apollostack/react-apollo#267]
I tried to follow the [doc](http://dev.apollodata.com/react/redux.html#creating-a-store) to integrate Apollo with an existing store, but encountered the error `Existing store does not use apolloReducer. Please make sure the store is properly configured and "reduxRootSelector" is correctly specified.`

The doc speaks of `reduxRootKey` whereas the error message speaks of `reduxRootSelector`. I have the feeling the code [changed](https://github.com/apollostack/react-apollo/issues/220) recently, and doc wasn't updated.

NB: I did add the apollo reducer as `apollo: client.reducer()` within my existing redux `combineReducers`. I then injected the `store` in `ApolloProvider` along with the `client`.

I tried adding `reduxRootSelector: 'apollo'` to the `ApolloClient` constructor, with same error message.

**Comment by helfer** [comment]
reduxRootKey was deprecated, but it's still supported, so we'll need to update the docs. The rootSelector should be a function.

For your actual issue, are you using an external redux store? If so, are you constructing it with the apollo reducer as specified in the docs, and then using the apollo middleware?

**Comment by stubailo** [comment]
Yeah, this sounds like you might not have added the middleware correctly.

**Comment by sedubois** [comment]
Yes tried to integrate into `react-boilerplate` which has its own store, here it is in case you understand it 😁 https://github.com/sedubois/belong/compare/gql...apollo

**Comment by GGAlanSmithee** [comment]
A clarification for anyone else having this issue...

```javascript
new ApolloClient({
    reduxRootSelector: state => state.apollo // your apollo reducer key
})
```

...is what needs to be added.

**Comment by DenisNeustroev** [comment]
Hi @sedubois I think you should pass the immutable prop to ApolloProvider `<ApolloProvider immutable store{...} client={...}>` and change reduxRootSelector to `reduxRootSelector: (state) => state.get('apollo')`

**Comment by sedubois** [comment]
Thanks I'll keep it in mind if I play with that project again. (Note that my original issue was that I couldn't get Apollo to work, even when specifying neither `reduxRootSelector` nor `reduxRootKey`, so probably my issue was elsewhere.)

**Comment by sedubois** [comment]
By the way I had briefly tried the suggestion with react-boilerplate but still had same issue. Actually a similar issue was created here: https://github.com/apollostack/apollo-client/issues/898

**Comment by DenisNeustroev** [comment]
I have a fully worked app with RBP and Apollo, there is no any issues. I can send example of integration.

**Comment by DenisNeustroev** [comment]
https://github.com/mxstbr/react-boilerplate/issues/1041#issuecomment-260126495

**Comment by oklas** [comment]
For case where immutable states in redux and some like `redux-immutable` is used selector must be like this:

``` jsx
new ApolloClient({
  reduxRootSelector: state => state.get('apollo'),
})
```
