### ISSUE TITLE
Automatically handle loading and failure renders

### ISSUE THREAD

**Issue by sedubois** [apollostack/react-apollo#268]
Hi and apologies again if this is documented somewhere, couldn't track it down. If possible, documentation would be needed.

It seems Apollo requires to manually handle cases when data is not yet available in a view, or when a failure occurs, leading to more boilerplate/bloat code.

Like in [Relay](https://facebook.github.io/relay/docs/api-reference-relay-root-container.html#renderloading), it should be possible for the developer to just "forget" about loading and failure cases and trust that a view is rendered only when data is available. (Of course, with the option of being able to configure custom failure and error rendering.)

**Comment by seeden** [comment]
You can simply create component/decorator with this functionality based on loading property

**Comment by sedubois** [comment]
@seeden thanks, but that's something to add on every component? What I mean is that specific handling loading/error cases should be something opt-in. In general shouldn't need to think about that for each and every component, things should "just work" like in Relay.

**Comment by seeden** [comment]
@sedubois what if you don't want to use it because you want to show something else?

**Comment by sedubois** [comment]
@seeden Relay allows to configure the renders, if the default behaviour isn't appropriate for your case (see [doc](https://facebook.github.io/relay/docs/api-reference-relay-root-container.html#renderloading)).

**Comment by seeden** [comment]
@sedubois you need to use graphql that means you can use your own instead of graphql which will use graphql inside your own component. But I agree it will be nice to have it in the graphql too

**Comment by jbaxleyiii** [comment]
closing in favor of #272
