### ISSUE TITLE
Errors regarding synthetic events with basic modification on the starter kit

### ISSUE THREAD

**Issue by ciwolsey** [apollostack/react-apollo#27]
When clicking on the refetch button on the starter kit  I get the following:
https://slack-imgs.com/?c=1&url=http%3A%2F%2Fi.imgur.com%2FbbbbqFA.png

All my packages and npms are up to date in terms of what has been published.

Repo for reproduction:
```
git@github.com:ciwolsey/apollo-issue-synthetic-events.git
```
Run this from /imports/ to restore my db:
```
mongorestore --host 127.0.0.1 --port 3001
```
Then in browser hit the refetch button and check browser console.

**Comment by ciwolsey** [comment]
Pulled in changes to react-starter-kit from last 24 hours and remade my app with it, no more errors.

**Comment by stubailo** [comment]
Oh glad it worked out! If you have a query error you should be able to see it in the UI as well!
