### ISSUE TITLE
Not getting the prop client from graphql() 

### ISSUE THREAD

**Issue by rnenjoy** [apollostack/react-apollo#273]
I have tried the examples and created an easy test:

```
render() {
    return (
      <ApolloProvider client={this.client}>
        <PostList />
      </ApolloProvider>
    );
  }
```

```
class PostList extends Component {
	constructor(props) {
		super(props)
   	console.log(props)
  }
export default graphql(gql`MY QUERY`)(PostList);
```

However my console.log shows that the props only holds the data object. Should it not also give me access to the apollo client from the higher order component ApolloProvider gives? withApollo() works, but i thought graphql should do the same thing?

**Comment by TimMikeladze** [comment]
@rnenjoy The client is set in the context, not the props. https://github.com/apollostack/react-apollo/blob/master/src/ApolloProvider.tsx#L35

**Comment by tmeasday** [comment]
> Should it not also give me access to the apollo client from the higher order component ApolloProvider gives? withApollo() works, but i thought graphql should do the same thing?

Short answer: no :)

**Comment by dmk255** [comment]
@tmeasday I would love for the documentation to be more explicit about this. It's a little unfortunate that `graphql` doesn't pass the client prop into the child component. 

The documentation at http://dev.apollodata.com/react/higher-order-components.html#withApollo implies (to me) that `graphql` should be able to do everything that `withApollo` can.
