### ISSUE TITLE
Fragments are never used when two batch queries share a part

### ISSUE THREAD

**Issue by drFabio** [apollostack/react-apollo#278]
I have two pages that use the same data with diferent behaviours they have the following format:
```javascript
`
  query ($deviceId: Int!) {
    devices(id: $deviceId){
      ${infoRequiredFragments}
    }
    ssids(deviceId:$deviceId){
      ${SSiDRequiredFragments}
    }
  }
`

`
  query ($deviceId: Int!) {
    devices(id: $deviceId){
      ${infoRequiredFragments}
    }
    inventories(deviceId: $deviceId){
      ${inventoryRequiredFragments}
    }
  }
```
When traversing from page to page using react-router one of the pages  get the common part removed on the query sent to the server (devices) and so the required fragments that are saved arrive at the server as unused
## Steps to Reproduce
1. Make two batch queries with a common part and that use fragments
2. While your app is still loaded traverse to a component that has the common part (I am using react-router and these two components are pages)
3. Expect the apollo server to throw a 400 explaining that you have unused fragments

### Buggy Behavior

The comon query is removed but it's fragments are sent

### Expected Behavior

On the removal process (due to caching I assume) remove the used fragments as well

Describe what you think should actually happen.

### Version
- apollo-client@0.4.19
- react-apollo@0.5.6

**Comment by drFabio** [comment]
Closing as this [one](https://github.com/apollostack/apollo-client/issues/762) explain it better and is already handled

**Comment by stubailo** [comment]
Great, thanks!
