### ISSUE TITLE
Bug: fragments in fetch more are not handled

### ISSUE THREAD

**Issue by svrcekmichal** [apollostack/react-apollo#287]
If i use fragment in `fetchMore` query, it is not flatten and it throws error, which is somehow not good too `Schema type definitions not allowed in queries. Found: "${definition.kind}"`  

https://github.com/apollostack/apollo-client/blob/master/src/queries/getFromAST.ts#L38

Quick solution to fix this is to handle fragments in `fetchMore`, but what i propose is little bit more work. I propose to collocate query with fragments, so I believe to have one function `createQuery` which would accept query and fragments(similar to createFragment) is better solution. Only issue is if you use some loggic to determine which fragment you use, but i would like to see example of that, because i've got little bit of trouble with that 👍

**Comment by jbaxleyiii** [comment]
@svrcekmichal I think this is an AC issue yes?

**Comment by stubailo** [comment]
Yep! Fixed in the newest release: https://github.com/apollostack/apollo-client/pull/842
