### ISSUE TITLE
fetchMore has no support for fragments

### ISSUE THREAD

**Issue by seeden** [apollostack/react-apollo#290]
I am trying to do fetchMore with fragments. But without any success
I tried next syntax but it is not supported

```js
return fetchMore({
   query,
   fragments,
   variables: {
     cursor,
   },
   updateQuery,
});
```

Am I missing something?

Currently we are using same syntax in the graphql decorator but it is not supported in the fetchMore syntax

**Comment by seeden** [comment]
I created same issue in the apollo-client because I found that you are using just fetchMore from apollo-client

**Comment by stubailo** [comment]
Thanks!
