### ISSUE TITLE
Proposal: move query in graphql HOC

### ISSUE THREAD

**Issue by svrcekmichal** [apollostack/react-apollo#294]
Is there some reason why query is first argument of graphql HOC? Wouldn't it be better if pass it in options under `query` key like it is in `fetchMore`? It would be awesome if we can select query depending on props passed to parrent component and also if https://github.com/apollostack/apollo-client/issues/853 will be approved it would make perfect sense

**Comment by jbaxleyiii** [comment]
@svrcekmichal that is actually and API we moved away from. Here is more info detailing the design behind the current API https://github.com/apollostack/react-apollo/issues/238#issuecomment-250652349
