### ISSUE TITLE
Example for Next.js

### ISSUE THREAD

**Issue by sedubois** [apollostack/react-apollo#295]
The new [next.js](https://github.com/zeit/next.js) framework looks quite promising, it would be awesome to have an example of integration with Apollo 😃 Especially as it does not (currently) expose a root-level routing component. (please close issue if you think it should be figured out on next.js side...)

**Comment by jbaxleyiii** [comment]
I'd love that! Been wanting to try out next.js!

**Comment by jbaxleyiii** [comment]
@sedubois do you have any links or any idea what would need to be added?

**Comment by sedubois** [comment]
Well, this works but I guess it creates a separate Apollo store per page...

https://github.com/sedubois/realate

**Comment by jbaxleyiii** [comment]
Does that work with SSR out of the box?

**Comment by sedubois** [comment]
@jbaxleyiii yes, at least that is the claim

**Comment by stubailo** [comment]
Does Next have an example with Redux? I imagine Apollo would be initialized and provided in exactly the same way.

**Comment by sedubois** [comment]
Indeed, here it is: https://github.com/zeit/next.js/wiki/Redux-example

The Redux client-side trick is:
```
if (!window.store) {
  window.store = createStore(reducer, initialState, middleware);
}
```

So I guess the only choice is to manually configure Apollo with such an external store: `<ApolloProvider store={store} client={client}>`.

I propose to close this and any next.js Apollo example could be added in their wiki.

**Comment by sedubois** [comment]
The example is being developed here, and it's not trivial:

https://github.com/zeit/next.js/issues/106

**Comment by stubailo** [comment]
Cool, let me know if I can help at all, other than the SSR bug. But yeah, attaching the store as a global variable could work I suppose. Just need to make sure it doesn't end up setting a global variable on the server during SSR!

**Comment by sedubois** [comment]
Thanks 😊 discussion continues in that other thread.
