### ISSUE TITLE
Server not rendering data

### ISSUE THREAD

**Issue by jasonnathan** [apollostack/react-apollo#296]
I am trying to render my app from the server  and everything works, for the most part. When I `curl localhost:3000`, I get generated html returned. However, I cannot seem to get past getting data to load on the server. I suspect it is simply because the data is not available yet - which is completely understandable on the client side. 

This component is loaded on both server and client: 
```jsx
const abstractPostsList = ({data}) =>{
  return data.loading ? (<Loader type="ball-triangle-path" />): (
    <StaggeredMotion
      defaultStyles={[...data.posts].map(() => {return {h: 0.1}})}
      styles={
        prevStyles =>
          prevStyles.map((_, i) => {return { h: spring(prevStyles[i - 1].h)}})
      }
    >
      {interpolatingStyles => <ul className="post-list">
        {interpolatingStyles.map((style, i) => {
          return (
            <li key={data.posts[i].slug} style={{opacity: style.h}}>
              <Post post={data.posts[i]} />
            </li>
          )
        })}
        </ul>
      }
    </StaggeredMotion>
  )
}

// We then can use `graphql` to pass the query results returned by MyQuery
// to MyComponent as a prop (and update them as the results change)
const PostsList = graphql(getPosts)(abstractPostsList);
export default PostsList;
```

This all works on the client. The `<Loader />` loads first and the `<Post />s` come animating in shortly after. However, `curl localhost:3000` returns the `<Loader />` component. I understand why it does, just don't know how to work around it. Can't I block the rendering until the data is ready? (At least on the server?)

### Packages
- apollo-client@^0.4.22
- react-apollo@^0.5.14
- METEOR@1.4.2
- reactrouter:react-router-ssr

**Comment by jbaxleyiii** [comment]
@jasonnathan where are you doing your SSR? Are you using `getDataWithTree` to prefetch all of the data?

**Comment by jbaxleyiii** [comment]
If I remember, with `reactrouter:react-router-ssr` you can do something like this:

```
preRender() { awaitAll(getDataFromTree(<App/>) }
```

**Comment by jasonnathan** [comment]
No, I was just reading about that, but I got all confused because there seemed to be an existing implementation via `meteor-react-router-ssr` here https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L85

Right, I'll try that!

**Comment by jbaxleyiii** [comment]
Yep! That package preforms the SSR for you. So you should be able to use that hook, and Meteor's Fiber implementation of promise to prefetch all of your data!

**Comment by jasonnathan** [comment]
Ok, I tried that, now I'm getting another error:

````
Sun Oct 30 2016 20:46:22 GMT+0800 (SGT) 'error while server-rendering' 'TypeError: this.all is not a function
    at Function.all (native)
    at Function.Promise.awaitAll (.meteor/packages/promise/.0.8.8.18xaxir++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:31:30)
    at Object.preRender (index.jsx:40:38)
    at packages/reactrouter:react-router-ssr/lib/server.jsx:188:23
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at generateSSRData (packages/reactrouter:react-router-ssr/lib/server.jsx:181:29)
    at sendSSRHtml (packages/reactrouter:react-router-ssr/lib/server.jsx:107:25)
    at packages/reactrouter:react-router-ssr/lib/server.jsx:94:13
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14\n => awaited here:
    at Function.Promise.awaitAll (.meteor/packages/promise/.0.8.8.18xaxir++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:31:12)
    at Object.preRender (index.jsx:40:38)
    at packages/reactrouter:react-router-ssr/lib/server.jsx:188:23
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at generateSSRData (packages/reactrouter:react-router-ssr/lib/server.jsx:181:29)
    at sendSSRHtml (packages/reactrouter:react-router-ssr/lib/server.jsx:107:25)
    at packages/reactrouter:react-router-ssr/lib/server.jsx:94:13
    at runWithEnvironment (packages/meteor.js:1176:24)
    at packages/meteor.js:1189:14
    at node_modules/react-router/lib/match.js:67:5'
````

**Comment by jbaxleyiii** [comment]
@jasonnathan that looks like an issue with the Meteor Promise implementation. Not sure if it is a bug there or not though. I don't see react-apollo in the strack trace

**Comment by jasonnathan** [comment]
Thanks @jbaxleyiii, all sorted. For anyone else getting this bug, it is related to https://github.com/nodejs/node/issues/5687 where `Promise.all` expects an array an isn't getting one. In my case, I was only resolving a single endpoint and changing `awaitAll` to `await` solved it.

The only issue I am still having is:
````
Warning: React attempted to reuse markup in a container but the checksum was invalid
````
Which seems to be related to this https://github.com/apollostack/react-apollo/issues/258 (I hope).

**Comment by ansonla3** [comment]
@jasonnathan  how can you do SSR with Meteor?

do you have apollo server that is running on a standalone apollo server node app? 
I just trying to find out how to do SSR with meteor apollo , but have no idea.

**Comment by jbaxleyiii** [comment]
@ansonla3 check out https://github.com/apollostack/react-apollo/tree/master/examples/meteor

**Comment by ansonla3** [comment]
@jbaxleyiii cool! check it out now. thanks very much!!
