### ISSUE TITLE
Fragment.propType.isRequired undefined

### ISSUE THREAD

**Issue by sedubois** [apollostack/react-apollo#299]
Taking a peek at the new [documentation](https://github.com/apollostack/react-docs/pull/90) for fragments, I got this code working (simplified):

```js
// Users.js
import React from 'react';
import gql from 'graphql-tag';
import apollo from './Apollo';
import UserPreview from './UserPreview';

const Users = props => (
  <div>
    {props.data.allUsers.map(u => <UserPreview key={u.id} user={u} />)}
  </div>
);
const query = gql`{
  allUsers {
    id
    ...UserPreviewUser
  }
}`;
const withData = apollo(query, {
  options: {
    fragments: UserPreview.fragments.user.fragments(),
  },
});
export default withData(Discover);
```
```js
// UserPreview.js
import React from 'react';
import gql from 'graphql-tag';
import Fragment from 'graphql-fragments';

function UserPreview({ className, user }) {
  return <p>{`${user.givenName} ${user.familyName}`}</p>;
}
UserPreview.fragments = {
  user: new Fragment(gql`    
    fragment UserPreviewUser on User {
      givenName
      familyName
    }
  `),
};
UserPreview.propTypes = {
  user: UserPreview.fragments.user.propType.isRequired,
};
export default UserPreview;
```

Although everything works, I get the console error `Warning: Failed prop type: UserPreview: prop type `user` is invalid; it must be a function, usually from React.PropTypes.`

If I remove `isRequired`, the warning disappears. Maybe `isRequired` is missing from the fragment propType implementation?

**Comment by tmeasday** [comment]
Hi @sedubois.

I guess we can take this conversation to https://github.com/apollostack/graphql-fragments but the short answer is you don't need to (and shouldn't) use `isRequired` for a `fragment.propType`. They are always required. 

I'm not sure if there is a valid use case where they are not required? If we can think of one perhaps we should change the default, add an `isRequired` version, and update the docs.

**Comment by sedubois** [comment]
OK I agree that they are required, I just found confusing that the API is incoherent with what's done in React/Relay proptypes. Here the propTypes is implicitly required, whereas it's flagged explicitly in React/Relay. (Might confuse people.)

**Comment by stubailo** [comment]
Interestingly, Relay doesn't even have proptypes for fragments: https://facebook.github.io/relay/docs/api-reference-relay-proptypes.html

**Comment by tmeasday** [comment]
@stubailo what do you think? I'm inclined to make it optional by default and add an `isRequired()`, this has confused a couple of people already.

**Comment by stubailo** [comment]
Sounds great! Let's talk on the other issue.
