### ISSUE TITLE
Experience with mapQueriesToProps

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/react-apollo#30]
first i'll say, `mapQueriesToProps` is pretty cool! To me, this function means we'll be mapping the result of a graphql query. Which in fact we do

```
{
  loading: false,
  result: {
    posts: []
  }
}
```

My question is, why tuck it away under a results key? Wouldn't it be nice to just have our prop
```js
{
  loading: false,
   posts: []
} 
```
I would then in my component much rather do 

```js
function App({postsData}) {
  const { posts = [], loading } = postsData;
  if ( loading) {
    return <Loader/>
  }
  return (
    <div>{posts.map(({ title }) => {
      return (
        <div>
          <h1>{title}</h1>
        </div>
      )
    })}</div>
  )
}

const AppWithData = connect({
  mapQueriesToProps() {
    return {
      postsData: {
        query: `
            {
              posts {
                title
              }
            }
          `
      }
    };
  }
})(App);
```

Essentially when the query yields, can we just extend this state structure? If you guys are down for this change, I can make it happen

**Comment by jbaxleyiii** [comment]
@abhiaiyer91 💯 go for it! Looks great!

**Comment by jbaxleyiii** [comment]
When you do it, will you add a warning about key collision of someone uses `loading` or `errors` as the prop key?

**Comment by abhiaiyer91** [comment]
Yeah i think in mutations we still would want to interact with the values of our data directly rather tucked away in results. And checking for this data should be best practice regardless if result existed or not.

**Comment by jbaxleyiii** [comment]
@abhiaiyer91 PR https://github.com/apollostack/react-apollo/pull/31
