### ISSUE TITLE
TypeError: Cannot read property 'getApolloState' of undefined

### ISSUE THREAD

**Issue by rattrayalex** [apollostack/react-apollo#304]
at server.ts:109:44

When you call `renderToStringWithData` with an app tree that does not include any graphql queries, the above error is thrown. It seems this is because `client.queryManager` is undefined; presumably it is only added to `client` when a query is found. 

I tried "fixing" this by changing the line to:
```
let apolloState = client.queryManager ? client.queryManager.getApolloState() : { queries: [] };
```

Then it turned out that `client.store` was undefined. I assume this had the same cause. In this case, my workaround was to use `(context.client.store || context.store).getState()` instead of `context.client.store.getState()`. 

When I made these changes, it works, but clearly there is a deeper issue... unfortunately I could not find it. 

### Version
- apollo-client@0.5.0
- react-apollo@0.5.13

**Comment by rattrayalex** [comment]
Ah, combing through the source, it looks like `initStore()` needs to be called on `client`. It doesn't seem likely that will cause problems to do manually, since it's a public method and doesn't take parameters. Not sure why it isn't called within the constructor – assuming something related to tests. 

I'll submit a PR shortly.

**Comment by tmeasday** [comment]
@rattrayalex do you think we are OK to close this now the SSR code doesn't run this path?

**Comment by rattrayalex** [comment]
Yes, I believe so! I haven't actually been able to try it yet unfortunately but can't imagine this would persist. I'll reopen if so.
