### ISSUE TITLE
Selector and business logic in apollo

### ISSUE THREAD

**Issue by bojandragojevic** [apollostack/react-apollo#309]
We know that with redux if you want to apply some additional logic on your data response in state before you pass it to component you can do it in selector. But since with apollo you connect data response directly to component I don't know where to apply this logic, here we do not have selectors.

so we know store can look like this if we use redux and apollo
```
const state = {
  redux: {// application state},
  apollo: {// apollo state and data}
}
```
So for redux you would select piece of state and pass it mapStateToProps and before you pass it you can apply some business logic to selected peace of state, but how to apply it to apollo peace of state?

**Comment by adam-bernau** [comment]
Hi @bojandragojevic, have you figured out how to do it?
 We have same problem :-(

**Comment by bojandragojevic** [comment]
No I did not figure it out, Seams that for project where we will use graphql we will use https://github.com/kadirahq/lokka instead apollo. This is for us important to be able in selectors apply business logic. With lokka that is possible.

**Comment by medv** [comment]
Correct me if I'm wrong (I'm just starting with apollo), but is this not described [here](http://dev.apollodata.com/react/redux.html)? You graphql-connect your already redux-connected component so you still have the redux selector function.

**Comment by stubailo** [comment]
Hi, have you seen the part of the docs that describes how to transform your data before passing it down? I think it's exactly what you are looking for.

http://dev.apollodata.com/react/queries.html#graphql-props

We use it very heavily in the example app, I'd suggest taking a look at that as well: https://github.com/apollostack/githunt-react

**Comment by leonardoanalista** [comment]
The HOC @graphql takes 2 params. First the query, second this config: http://dev.apollodata.com/react/api-graphql.html#graphql-config-props
use `props` to transform data before handing over to your components.
