### ISSUE TITLE
Error in documentation for Pagination

### ISSUE THREAD

**Issue by ryannealmes** [apollostack/react-apollo#310]
Looking at the [documentation](http://dev.apollodata.com/react/pagination.html#numbered-pages) on pagination. 

```javascript
props({ data: { loading, feed, currentUser, fetchMore } }) {
    return {
      loading,
      feed,
      currentUser,
      loadMoreEntries() {
        return fetchMore({
          // query: ... (you can specify a different query. FEED_QUERY is used by default)
          variables: {
            // We are able to figure out which offset to use because it matches
            // the feed length, but we could also use state, or the previous
            // variables to calculate this (see the cursor example below)
            offset: feed.length,
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            if (!fetchMoreResult.data) { return previousResult; }
            return Object.assign({}, previousResult, {
              // Append the new feed results to the old one
              feed: [...previousResult.feed, ...fetchMoreResult.data.feed],
            });
          },
        });
      },
    };
  },
})(Feed);
```
Shouldn't the offset being set in `loadMoreEntries` be something like `pageSize * pageNumber - 1`. 

For example if I am on page 1 with a page size of 10 and I click on page 3, based on the example, my offset will be 10, when it should be 20.

**Comment by tmeasday** [comment]
I think props gets called again with a new feed after your first `loadMoreEntries`? Have you tried it @ryannealmes?

**Comment by ryannealmes** [comment]
@tmeasday, note I am not saying load entries is not being called. I am saying the example does not return the correct data when it is called. In pagination your offset is based on the number you click 1,2,3,4,5. If I click 3 my offset is not the `feed.length`.
 
Hence the example is invalid.

Maybe I missing something?

I know that if you have loaded entries sequentially then the offset would most likely be correct, but if you skip pages I think the offset is wrong.

**Comment by tmeasday** [comment]
Oh. Well this is example is intended as an "infinite scroll" type situation.

If you wanted to do a paged style approach, you'd need to pass an offset argument into the `loadMoreEntries` callback.

**Comment by ryannealmes** [comment]
Ah ok. From the documentation it felt like it was talking about numbered pages and not infinite scrolling. It may be good to make this distinction. 

Just for reference this is what is describing the functionality.

_Offset-based pagination — also called numbered pages — is a very common pattern, found on many websites, because it is usually the easiest to implement on the backend. In SQL for example, numbered pages can easily be generated by using OFFSET and LIMIT._

Thanks for clearing that up though. Appreciate the time! Loving apollo!

**Comment by tmeasday** [comment]
Yeah, I can see where you are coming from. I think the wording is a bit awkward there. Perhaps you can suggest an improvement via a PR?
