### ISSUE TITLE
Authentication with header missing Bearer prefix

### ISSUE THREAD

**Issue by sedubois** [apollostack/react-apollo#320]
I copied the code snippet about authenticating with a header from this page: http://dev.apollodata.com/react/auth.html

But didn't pay close enough attention that it was missing the "Bearer" part, and the result was that authentication was simply ignored.

1. change the doc to something like this? `req.options.headers.authorization = token ? `Bearer ${token}` : null`
2. throw an error when it has a wrongly formatted auth header, instead of silently ignoring it?

**Comment by stubailo** [comment]
What's your backend?

**Comment by sedubois** [comment]
@stubailo Graphcool

**Comment by tmeasday** [comment]
Can we move this issue to `apollo-client`? This doesn't seem like an RA issue.

**Comment by sedubois** [comment]
@tmeasday sure
