### ISSUE TITLE
The `graphql` HOC should uniquely declare passed fragments

### ISSUE THREAD

**Issue by jnwng** [apollostack/react-apollo#325]
### Steps to Reproduce

1. Pass in multiple instances of the same fragment to the `graphql` HOC.
```js
import { createFragment } from 'apollo-client';
const someFragment = createFragment(gql`
  fragment SomeFragment on SomeEdge {
    someField
  }
`);

graphql(gql`
  query {
    SomeEdge {
      ...SomeFragment
    }
  }
`, {
  options: {
    fragments: [someFragment, someFragment]
  }
});
```
2. See that the query that gets sent looks like
```graphql
query { someEdge { ...SomeFragment } }
fragment SomeFragment on SomeEdge { someField }
fragment SomeFragment on SomeEdge { someField }
```

NOTE: Of course, this is a very trivial example. Where this occurs in a real application is when two fragments in separate branches of a particular fragment tree _both_ declare a dependence on the same fragment, and otherwise have no knowledge that this fragment has already been registered. This HOC will flatten that tree regardless, and that's when the duplicate declarations occur.

### Buggy Behavior
The GraphQL spec specifies that a [fragment's name must be unique within a document](https://facebook.github.io/graphql/#sec-Fragment-Name-Uniqueness) (even if these two fragments are actually the same fragment).

The `graphql` HOC can safely remove the second declaration since we already know its been registered. We're able to safely guard against duplicate fragment names (where the fragment itself is different) in [createFragment](https://github.com/apollostack/apollo-client/blob/8030a2f/src/fragments.ts#L39-L43)

### Expected Behavior

The query that is sent should look like:
```graphql
query { someEdge { ...SomeFragment } }
fragment SomeFragment on SomeEdge { someField }
```

### Version
- apollo-client@0.5.1
- react-apollo@0.5.16

**Comment by jnwng** [comment]
I actually created a (potential) solution to this before seeing that I should open an issue first - see that pull request [here](https://github.com/jnwng/react-apollo/pull/1). If that seems suitable, happy to make a pull against this repo and reference this issue, as noted in the pull request template.

**Comment by stubailo** [comment]
Thanks for the detailed description of the issue!

Looks like this is the same bug: https://github.com/apollostack/apollo-client/issues/897

As I mentioned on your PR probably the right place to put it is in `apollo-client`, here: https://github.com/apollostack/apollo-client/blob/372bca9881b374caf56d0cbd0795a88dcc13ec0f/src/queries/getFromAST.ts#L150

**Comment by stubailo** [comment]
(In the `apollo-client` bug report there is also a workaround, by the way: https://github.com/apollostack/apollo-client/issues/897#issuecomment-260087424

**Comment by stubailo** [comment]
(If it's OK, let's close this one and talk on apollostack/apollo-client#897)

**Comment by jnwng** [comment]
Yep, sgtm. Will see if the fix can be ported to the area you pointed out.
