### ISSUE TITLE
Suggestion: add getWrappedInstance to withApollo

### ISSUE THREAD

**Issue by SachaG** [apollostack/react-apollo#331]
Unless I'm mistaken I think the `withApollo` HoC doesn't have a `getWrappedInstance` method, unlike the `graphql` wrapper. Maybe one could be added?

**Comment by stubailo** [comment]
Good idea - send a PR?

**Comment by jbaxleyiii** [comment]
@SachaG I'm all for this, it makes sense to have with both. I'm curious, what do you have a need to get the wrapped instance for? I've never had the need to do and have wondered 👍

**Comment by SachaG** [comment]
@jbaxleyiii well let's say you have an ES6 class `MyComponent` with a `submitForm` event handler as one of its methods, and you then wrap it with `withApollo`. If do `const Foo extends MyComponent` to declare a new component, `Foo` won't have access to the `submitForm` method. So you'd want to be able to do `const Foo extends MyComponent.getWrappedInstance()` to access the original component before it's wrapped.

**Comment by helfer** [comment]
@SachaG any progress on this? 🙂

**Comment by SachaG** [comment]
Oh sorry, I got sidetracked. Also @xavcz mentioned he might want to work on this. 

Personally what held me up is that I haven't actually worked on NPM packages before (I'm still a Meteor guy at heart ;), so I don't have the workflow set up. Would you have any pointers on that by any chance?
