### ISSUE TITLE
Is there a way to make queryVariables be available on reducer option?

### ISSUE THREAD

**Issue by drFabio** [apollostack/react-apollo#332]
Currently it seems that unlike [updateQueries](http://dev.apollodata.com/react/cache-updates.html#updateQueries), the [reducer](http://dev.apollodata.com/react/cache-updates.html#resultReducers) option can't get the query variables on the update.

Was this by design? Is there a way to achieve it or it is a constraint of some sort?

One example of why this may be needed is this:

- Suppose a query has a sort param that can have a field and a direction.
- Suppose that a mutation added a new item to that query and this query wants to be updated.
- With updateQueries there is a parameter [queryVariables](https://github.com/apollostack/react-apollo/blob/1c85c07996c529d17d6c04859717a5017aa8a246/test/react-web/client/graphql/mutations.test.tsx#L329) That allow it.
- With reducer this parameter does not seem to be reachable making it impossible to add the newly added item on the right place.

Thanks in advance

**Comment by helfer** [comment]
@drFabio this issue belongs on Apollo Client, react-apollo just passes it through.

**Comment by drFabio** [comment]
Ok will close and reopen it then. 
Thanks
