### ISSUE TITLE
(SSR) Child's fetchData called on vanilla react-redux HOCs

### ISSUE THREAD

**Issue by voodooattack** [apollostack/react-apollo#337]
Higher order components created using `react-redux`'s `connect()` function expose all statics of the wrapped components, as per [this description](https://github.com/reactjs/react-redux/blob/master/docs/api.md#static-methods), thus exposing `fetchData` of the child component, which gets called before `connect()` can provide any required props from the store.

## Steps to Reproduce

In this example I reference a `locale` field on the `redux` store. It gets fetched from the `redux` store and passed on to the `react-apollo` HOC, which passes `locale` to a GraphQL query.

```js
function mapStateToProps({ locale }) {
  return { locale };
}

function mapDispatchToProps(dispatch) {
  return {
    setLocale(locale) { dispatch({ type: 'SWITCH_LOCALE', locale }); }
  }
}

export const withLocale = connect(
  mapStateToProps,
  mapDispatchToProps
)(Component);

export const withTranslateMessage = Component => withLocale(
  graphql(gql`
    query($localeCode: String!, $message: String!, $variables: Value) {
      translateMessage(localeCode: $localeCode, message: $message, variables: $variables)
    }
  `, {
    options({ locale, message, variables }) {
      return {
        variables: {
          localeCode: locale,
          message,
          variables
        }
      }
    },
    props({ /*ownProps,*/ data: { loading, error, translateMessage } }) {
      if (loading || error)
        return { loading, error };
      return {
        translatedMessage: translateMessage,
      };
    }
  })(Component)
);

/**
 * The FormattedMessage component handles message translation.
 */
class FormattedMessageComponent extends React.Component {
  static propTypes = {
    component: React.PropTypes.any,
    message: React.PropTypes.string.isRequired,
    translatedMessage: React.PropTypes.string,
    variables: React.PropTypes.object,
    componentProps: React.PropTypes.object
  };
  render() {
    // the default html component is <span />
    const component = this.props.component || 'span';
    // fallback to children if translation is not available
    const message = this.props.translatedMessage || this.props.children;
    return React.createElement(component, this.props.componentProps, message);
  }
  get message() { return this.props.translatedMessage; }
}

export const FormattedMessage = withTranslateMessage(FormattedMessageComponent);
```

### Buggy Behavior

This fails to render because `fetchData` gets exposed by `connect()`, which gets picked up first, thus triggering a `GraphQLError` about missing the `localeCode` argument.

### Expected Behavior

Ideally, `react-apollo` should never call the static `fetchData` on higher-order components generated with `connect`.

### Workaround

Delete `fetchData` from `connect()`'s HOC.

```js
export const withLocale = Component => {
  const result = connect(
    mapStateToProps,
    mapDispatchToProps
  )(Component);
  delete result.fetchData;
  return result;
};
```

### Version
-    "apollo-client": "^0.5.1",
-    "react-apollo": "^0.5.16",
-    "react-redux": "^4.4.6"

**Comment by tmeasday** [comment]
Thanks @voodooattack.

As an aside, I wonder if we should even be using a static method for this at all.

Do you have any good ideas about how we could go about fixing this? The idea is that `fetchData` would be a generic API that isn't just RA-specific.

**Comment by voodooattack** [comment]
Maybe use an internal `Symbol()` instead of a named function?

I like the idea of a generic `fetchData` as well, had many a situation where I could've used that.

**Comment by tmeasday** [comment]
> Maybe use an internal Symbol() instead of a named function?

Yeah I think there are a probably a few ways to do it that would ultimately lose genericity. Maybe that's the best we can do if hoisting is normal..

**Comment by tmeasday** [comment]
See #55

**Comment by voodooattack** [comment]
Okay, I'm closing this. Thanks for the quick solution!
