### ISSUE TITLE
Multiple simultaneous queries with same variables are not merged

### ISSUE THREAD

**Issue by wmertens** [apollostack/react-apollo#338]
## Steps to Reproduce

1. Make a component like
```js
@connect(state => ({foo: ...}))
@graphql(gql`query ...($foo: ...) {...}`)
class MyComponent extends Component {...}
```
  
2. put the component in the app twice `<MyComponent/><MyComponent/>`.

### Buggy Behavior

Look at the network tab when the components are mounted - the query is ran twice, with the same variable `foo`.

### Expected Behavior

It should only run the query once and provide the results to both components. After all, the variables are the same, and the query is the same object.

### Version
- apollo-client@0.5.6
- react-apollo@0.6.0

**Comment by TSMMark** [comment]
related to #336?

**Comment by tmeasday** [comment]
@wmertens what happens if you wait until the query has returned from the server before mounting the second component?

I would expect it to send 2 queries if the first is still in flight.

**Comment by wmertens** [comment]
@tmeasday Once the query completes it is served from cache as it should.

The problem is that not coalescing the same query in flight breaks the abstraction. `@graphql` is supposed to get the described data as efficiently as possible and if it doesn't do that, it means putting workarounds in place that damage the application code clarity.

So IMHO, this is a bug…

**Comment by wmertens** [comment]
I just realized that the in-flight coalescing should probably happen in apollo-client, I'll move the issue there.

**Comment by wmertens** [comment]
Closing this in favor of https://github.com/apollostack/apollo-client/issues/956
