### ISSUE TITLE
Mutation result and apollo cache update

### ISSUE THREAD

**Issue by callmephilip** [apollostack/react-apollo#343]
## Steps to Reproduce

I have a mutation updating a field on one of the items. Apollo [documentation](http://dev.apollodata.com/react/mutations.html) regarding mutation results says the following:

> Note that, in general, you don’t need to use the results from the mutation callback directly. Instead you should usually rely on Apollo’s id-based cache updating to take care of it for you. 

After successful completion of the mutation (confirmed via Redux store traces), I expect records to to be updated accordingly. The actual result is that the update does not occur. Once the app is reloaded, the updated record is displayed correctly.  

## Source code

```javascript
import { View, Text, ListView } from 'react-native';
import React, { Component, PropTypes } from 'react';
import styles from './styles';
import NoTodos from '../NoTodos';
import TodoItem from '../TodoItem';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

class TodoList extends Component {
  constructor() {
    super();

    this.renderRow = this.renderRow.bind(this);
  }

  renderList() {
    const { todos } = this.props;
    if (todos && todos.length !== 0) {
      const ds = new ListView.DataSource({
        rowHasChanged: (r1, r2) => r1 !== r2,
      });

      return (
        <ListView
          dataSource={ds.cloneWithRows(todos)}
          renderRow={this.renderRow}
        />
      );
    }

    return (
      <NoTodos />
    );
  }

  renderRow(todo) {
    return (
      <TodoItem
        todo={todo}
        key={todo.id}
        onToggleCompletion={this.props.toggleTodoCompletion}
      />
    );
  }

  render() {
    const { loading } = this.props;
    return (
      <View style={styles.container}>
        { loading ? <Text>Loading...</Text> : this.renderList()}
      </View>
    );
  }
}

const withData = graphql(gql`query todos { todos { id, text, isComplete } }`, {
  props: ({ data: { loading, todos } }) => {
    return {
      loading,
      todos,
    };
  },
});

const toggleCompletionMutation = gql`
  mutation toggleTodoCompletion($id: ID!) {
    toggleTodoCompletion(id: $id) {
      id, isComplete, text
    }
  }
`;

const withMutations = graphql(toggleCompletionMutation, {
  props: ({ mutate }) => ({
    toggleTodoCompletion: ({ id }) => mutate({ variables: { id } }),
  }),
});

TodoList.propTypes = {
  todos: PropTypes.array,
  toggleTodoCompletion: PropTypes.func.isRequired,
};

export default withMutations(withData(TodoList));
```

### Platform
- React Native

### Version
- apollo-client@0.5.6
- react-apollo@0.6.0

**Comment by tmeasday** [comment]
Hi @callmephilip. Are you using `dataIdFromObject`? Eyeballing your code it looks like it should work if that is setup properly.

Have you looked at https://github.com/apollostack/frontpage-react-native-app? It does something *very* similar and I know it works there!

**Comment by callmephilip** [comment]
@tmeasday thanks man! looks like this dataIdFromObject did the trick - i was misled by the comment in the section below saying "(Note: in 0.5.x, this is the default behavior)"

**Comment by tmeasday** [comment]
You're right, I've fixed that.
