### ISSUE TITLE
*Feature/Docs Request* Fire queries in Redux actions

### ISSUE THREAD

**Issue by savovs** [apollostack/react-apollo#348]
Hi guys, I'm trying to convert a REST app to Apollo and I have a bunch of thunk actions making rest requests. I prefer doing most things with actions and I thought, what if you could have an Apollo action for a specific query or have a query fire when a specific action happens:
```javascript
// REST
export const fetchSomething = () => ({
	type: 'FETCH_SOMETHING',
	payload: axios.get('http://84.9.10.41:3000/something'),
});

// GraphQL
export const runSpecificQuery = query => ({
	type: 'SPECIFIC_QUERY',
	payload: apollo(specificQuery),
});
```
If I just bind a query to a component, the data is stuck directly to it and isn't reflected in the Redux store, which feels a bit odd after learning Redux and it tells you to do everything with actions and reducers and that limitation is supposed to give you the benefits of the whole library.

I'm aware that Apollo uses APOLLO_QUERY actions under the hood, but I was wondering what you guys thought about this concept. I find myself drooling over #120 but still trying to understand if it's possible to have different actions for different queries with the state reflected in the Redux store.

**Comment by stubailo** [comment]
> If I just bind a query to a component, the data is stuck directly to it and isn't reflected in the Redux store

The data is in redux, in `apollo.data`.

Kind of the whole point of Apollo is managing the GraphQL-related actions and reducers for you. You still get all of the benefits of Redux, but without having to write any boilerplate. The benefits of Redux are understanding data flow and better dev tools, I don't think it's about boilerplate. In fact many Redux materials are now recommending structuring your reducers in a more generic way - in that sense you can think of Apollo as a pre-written "GraphQL data" reducer.

Anyway, what benefits are you looking for to get out of this approach, other than philosophical concerns about doing things via actions?

**Comment by savovs** [comment]
I'm looking for a recipe to fire queries when a function runs, rather than when a component loads. For things like search, form submission, etc. I think that's what led me to think about this.

**Comment by johnunclesam** [comment]
@savovs have you found something about that?

**Comment by bitrix1** [comment]
Hi, there are only ajax requests like https://blog.graph.cool/how-to-use-graphql-with-jquery-51786f0a59cb ?
