### ISSUE TITLE
This uses deprecated `createFragment`

### ISSUE THREAD

**Issue by SimenB** [apollostack/react-apollo#356]
See https://github.com/apollostack/apollo-client/pull/984#discussion_r90794327

## Steps to Reproduce

Use `graphql` export

### Buggy Behavior

I get a deprecation warning from react-apollo

### Expected Behavior

No deprecation warning

### Version
- apollo-client@0.5.11
- react-apollo@0.6.0

**Comment by tmeasday** [comment]
Thanks, @SimenB, fixed in https://github.com/apollostack/react-apollo/pull/357, trying to figure out why an unrelated test is failing.

**Comment by tmeasday** [comment]
I think this was fixed in v0.7.1

**Comment by SimenB** [comment]
Yup, no more warning. Thanks!
