### ISSUE TITLE
Container breaks after mutation, if mutation fetches partial data

### ISSUE THREAD

**Issue by jbuchermn** [apollostack/react-apollo#361]
Hello,

I'm very new to Apollo, so far I'm really happy about it. But there is one thing I keep seeing, that is a bug in my opinion. Let's say I have a graphql container with the following query

`{
  user {
    id
    group{
      id,
      members{[...]}
    }
  }
}`

i.e. a user may be assigned to a group (or group might be null). So now I'm running a mutation, that results in the user being assigned to a group:

`
mutation {
  assignToGroup([...]){
    user{
      group{
        id
      }
    }
  }
}
`

This mutation is run, while the other container is still mounted (but not inside that container). Now the result of the query is never passed to that container, instead the container is stuck on `loading: true`. Apollo-Client receives the results and, as far as I can make out, doesn't run into any problems (redux-logger gives a `loading: false` after APOLLO_MUTATION_RESULT).

Everything works if the mutation fetches the `members` node. I think the expected behaviour should be, that the container issues a refetch (at least it shouldn't be stuck on loading..)

This problem is not too severe in my use case, but it also appears in another setting. Let's say I do fetch the `members` child in the mutation (which is a list supporting pagination via variables, so in this case the variables would be `first: 10`), navigate back to the container. Everything works. I scroll down, a fetchMore is issued (setting a cursor variable, i.e. the variables are `first: 10, after: '...'`). If then, after this refetch, the mutation is issued again (fetching `members` - of a potentially different group - with `first: 10`), the same problem as above appears. react-apollo is stuck on `loading: true`.

Am I missing something here? Or is this an issue?

Thanks in advance

**Comment by tmeasday** [comment]
Hi @jbuchermn, this does sound like it could be an issue. Have you tried simplifying it a little bit?

Can you try and construct a simple reproduction? it's not totally clear what's happening here, but by the sounds of it the container shouldn't be `loading` at all.

**Comment by ARMGAMES** [comment]
@jbuchermn, I think i have same issue #368 
Please check it

**Comment by helfer** [comment]
Closing this in favor of #368 which seems to be the same bug/issue indeed but has a slightly clearer description.

**Comment by jbuchermn** [comment]
Yeah I think #368 is the same issue.
