### ISSUE TITLE
Component not receiving new props

### ISSUE THREAD

**Issue by marcgreenstock** [apollostack/react-apollo#365]
I'm unsure if this is a bug or if I'm missing something, but according to the [docs on watchQuery](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient\.watchQuery):

> [...] suppose you call watchQuery on a GraphQL query that fetches an person's first name and last name and this person has a particular object identifier, provided by dataIdFromObject. Later, a different query fetches that same person's first and last name and his/her first name has now changed. Then, any observers associated with the results of the first query will be updated with a new result object.

Can I assume that in the given example above, only the first and last name properties (i.e. only properties specified in the original query) will receive updates, and any new properties that have been retrieved in subsequent queries will not be propagated?

Take for instance the following queries:

```graphql
query getMyName {
   me {
     id
     firstName
     lastName
   }
}
```

```graphql
query getMyDetails {
   me {
     id
     firstName
     lastName
     email
   }
}
```

The first just gets the users `firstName` and `lastName`, and the second gets the `email` too. If `firstName` and/or `lastName` change on the server between queries then the component will receive the update, but it doesn't receive the `email`. Is this the expected behaviour?

I have `dataIdFromObject` setup as `o => o.id` and `id` is type specific.

### Version
- apollo-client@0.5.12
- react-apollo@0.6.0

**Comment by helfer** [comment]
@marcgreenstock yes, that is indeed the expected behavior. The object in the cache will contain all the fields, but each query will only get the data it asked for. Does that answer your question?

**Comment by marcgreenstock** [comment]
Thanks @helfer that makes it clear.
