### ISSUE TITLE
Update react-redux to 0.5.0

### ISSUE THREAD

**Issue by colevoss** [apollostack/react-apollo#369]
[react-redux@0.5.0](https://github.com/reactjs/react-redux/releases/tag/v5.0.0) released yesterday and includes many performance improvements along with new API's to use. It would be great to get `react-apollo` on this new version. 

It is backwards compatible so ideally we could just drop it in and be fine with no code change. That said it would be great to try to take advantage of some of the new features. I plan on doing some research to see what all this could do for react-apollo

**Comment by colevoss** [comment]
After looking at more source, I realized that this was prematurely created since react-apollo only uses react-redux for testing purposes.

Closing

**Comment by stubailo** [comment]
I bet if there are some big improvements in react-redux 5, we could use some similar ones in here. Of course the use case is pretty different but maybe they have some generic ideas about improvements for how React HoCs should work.
