### ISSUE TITLE
Getting "reducer not a function" when passing query functions as props

### ISSUE THREAD

**Issue by Sawtaytoes** [apollostack/react-apollo#370]
## Steps to Reproduce

1. Create a query var `QUERY`.
2. Send `data.fetchMore(QUERY)` down to another component.
3. Call the function in that component and the error will show up.

### apollo-client.jsx
```js
import ApolloClient, { createNetworkInterface } from 'apollo-client'

export const client = new ApolloClient({
  networkInterface: createNetworkInterface({
    shouldBatch: true,
    uri: '/api/graphql',
  }),
})
```

### tweets.jsx
This is a fairly simple example which is what's catching me.
```js
const GET_TWEETS = gql`
query GetTweets {
  tweets {
    content
    postTime {
      time
      unixTime
    }
    user {
      username
    }
  }
}`

class Tweets extends PureComponent {
  static propTypes = { data: PropTypes.object };
  static defaultProps = { data: {} };

  render() {
    const { data } = this.props
    return (
      <div>
        <TweetList tweets={data.tweets} refresh={() => data.fetchMore(GET_TWEETS)} />
      </div>
    )
  }
}

export default graphql(GET_TWEETS)(stylesLoader.render(Tweets))
```

**NOTE:** The `TweetList` component does **not** have `connect()` or Redux enabled in this test. I tried that in a different view, and it didn't help.

**You can find the full code here:**
https://github.com/Sawtaytoes/Twitter-Style-App-in-React/tree/feature/graphql

### Buggy Behavior

When I pass `()=> data.fetchMore()` or `input => mutate({ variables: { input })` as props, I get this error:
```
TypeError: reducer is not a function
    at mapFn (eval at <anonymous> (main.bundle.js:6389), <anonymous>:117:24)
    at eval (eval at <anonymous> (main.bundle.js:6389), <anonymous>:194:84)
    at Object.tryFunctionOrLogError (eval at <anonymous> (main.bundle.js:6587), <anonymous>:4:16)
    at ObservableQuery.updateQuery (eval at <anonymous> (main.bundle.js:6389), <anonymous>:194:41)
    at eval (eval at <anonymous> (main.bundle.js:6389), <anonymous>:122:19)
tryFunctionOrLogError @ VM41065:8
ObservableQuery.updateQuery @ VM41043:194
(anonymous) @ VM41043:122
```

I do have Redux in the app, but I was getting that error before I hooked up the store in the `ApolloProvider` component directly. Even after adding it to my list of reducers I still get this error.

### Expected Behavior

It should function the same as it does when the `graphql()` higher-order function is wrapping the element doing the querying without showing the error.

### Version
```json
"apollo-client": "^0.5.19",
"react": "^15.4.1",
"react-apollo": "^0.7.1",
```

**Comment by helfer** [comment]
@Sawtaytoes The error message here isn't good, but you need to define an updateQuery function and pass that along when you use `fetchMore`. Otherwise Apollo Client has no way of knowing how to update the data that's already in the store.

In your case you should just use the built-in `refetch` function though, because that seems to be what you want it to do.

**Comment by helfer** [comment]
I'll leave this issue open to make sure we don't forget to provide a better error message here.

**Comment by Sawtaytoes** [comment]
I changed to `refetch` yesterday after reading more documentation.

There was an Apollo blog article about updating from data calls, and it specifically said use `fetchMore` which was confusing. In fact, I found out about `refetch` by looking at the `data` object and seeing what properties I could call on it.

I appreciate your response :D.
