### ISSUE TITLE
Cannot find module 'react-apollo/server'

### ISSUE THREAD

**Issue by doranen** [apollostack/react-apollo#384]
## Steps to Reproduce
just upgraded to 0.7.2, getting this error on webpack build when trying to import { renderToStringWithData } from "react-apollo/server";

### Buggy Behavior

build breakage

### Expected Behavior

Should import correctly from documented path

### Version
- apollo-client@0.5.11
- react-apollo@0.7.2

**Comment by doranen** [comment]
maybe it's just react-apollo now?

**Comment by stubailo** [comment]
Yes you don't need to import from /server - that was the breaking change between 0.6 and 0.7. Let me know if you see some old documentation that has the other thing?

**Comment by doranen** [comment]
http://dev.apollodata.com/react/server-side-rendering.html

**Comment by stubailo** [comment]
Oh wow that's embarrassing - I thought for sure that would be updated. I'll open an issue there and if you have a moment send a PR? (I'm in mobile right now)

**Comment by doranen** [comment]
sure, as an aside, where do i see the changelogs?

**Comment by tmeasday** [comment]
https://github.com/apollostack/react-apollo/blob/master/Changelog.md

**Comment by doranen** [comment]
Whoops, totally missed it!
