### ISSUE TITLE
Can't call api of GraphQL HOC wrapped component

### ISSUE THREAD

**Issue by dcworldwide** [apollostack/react-apollo#388]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Wrap a component in the graphql HOC
2. When rendering the HOC component, define a ref 
3. Use the ref to attempt to call a function on the wrapped component
4. Function not found, because ref refers to the HOC, not the wrapped component

### Expected Behavior

I should be able to call methods of GraphQL wrapped components? 

### Version
- apollo-client@0.5.23
- react-apollo@0.5.13

Use case specific detail:
--------------------

- I have a user signup component (USC) that is designed as a wizard using http://www.material-ui.com/#/components/stepper.
- USC controls the flow between steps. 
- Each step, renders a GQL wrapped component. 
- I need each step component to implement an api (i.e. isValid(), saveStep())
- I need the USC to call this api, hence my issue.

**Comment by dcworldwide** [comment]
Apologies, I've just found http://dev.apollodata.com/react/higher-order-components.html#with-ref

**Comment by helfer** [comment]
@dcworldwide Thanks for documenting the solution. I hope it's okay if I close the issue since there's nothing we can do about it. The issue will still be searchable by others who have the same problem.

**Comment by bigstas** [comment]
> Issue 1
> 
> I need to use withRef http://dev.apollodata.com/react/higher-order-components.html#with-ref

I have your issue, this link is broken and I can't find anything on withRef anywhere.

**Comment by bigstas** [comment]
Ok I found the documentation about withRef, here is the [fresh link](https://www.apollographql.com/docs/react/basics/setup.html#graphql-config-withRef).
