### ISSUE TITLE
Module not found: Error: Can't resolve 'react-apollo'

### ISSUE THREAD

**Issue by marcelofpalves** [apollostack/react-apollo#398]
Problem: Cannot find 'react-apollo' when importing

### Version
- apollo-client@<0.6.0>
- react-apollo@<0.8.0>

I created a minimal repo to reproduce the issue.
https://github.com/marcelofpalves/react-apollo-crashing-example

The main entry on the package.json has this path:
```js
"main": "lib/index.js"
```
But in `node_modules/react-apollo/lib` there is no `index.js` on that folder.
Maybe there is an issue with the build.

Thank you.

**Comment by helfer** [comment]
Hm, did I not publish this correctly? 🤔

**Comment by helfer** [comment]
Set the `latest` tag to 0.7.2 while I try to figure out what's going on.

If I can't figure it out, we might need @jbaxleyiii 's help here.

**Comment by helfer** [comment]
Was just about to release 0.8.1, but I think @jbaxleyiii beat me to it. 😃

**Comment by helfer** [comment]
@marcelofpalves @Grmiade @pradel @JacobSoderblom Please give this comment a thumbs up if it works for you now, thumbs down if it doesn't. Thanks!

**Comment by marcelopereirascmspain** [comment]
@helfer thank you

I updated the example with v0.8.1 (https://github.com/marcelofpalves/react-apollo-crashing-example)
now it breaks with

```bash
ERROR in ./~/react-apollo/lib/browser.js
Module build failed: Error: Couldn't find preset "react-native" relative to directory "/Users/marcelo.pereira/Desktop/react-apollo-crashing-example/node_modules/react-apollo"
    at /Users/marcelo.pereira/Desktop/react-apollo-crashing-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
```

can anyone reproduce this?

**Comment by helfer** [comment]
@marcelopereirascmspain did you update your reproduction? It will hopefully help us figure out what's going on.

**Comment by marcelofpalves** [comment]
@helfer I did.
I put the link in the comment above. Hopefully it will help.

**Comment by helfer** [comment]
Ok, thanks! It's getting quite late here, so I hope someone else can pick this up tomorrow morning and fix it! 🙂

**Comment by marcelofpalves** [comment]
I see :) Thank you for your time!

**Comment by peitalin** [comment]
+1
I'm getting the same error with "react-apollo": "^0.8.1", and it went away after installing "babel-preset-react-native": "^1.9.1".

**Comment by chrisself** [comment]
For anyone who stumbles across this issue who is also using Webpack, I was able to resolve the react-native related error message by ignoring the node_modules folder in babel-loader:

```
{
  test: /\.jsx?$/,
  exclude: /node_modules/,
  loader: 'babel-loader',
  options: { }
}
```

**Comment by crisu83** [comment]
We also faced this issue, and in our case, the issue was that we had defined a `'react-apollo': 'react-apollo/lib/browser'` alias in our Webpack config to optimize our bundle size. Apparently, this doesn't work anymore for some reason, so removing this alias fixed our build.

**Comment by quangv** [comment]
I had this issue with `"react-apollo": "^2.1.6",`

`yarn add apollo-client` resolved it.

**Comment by aalfr494** [comment]
> I had this issue with `"react-apollo": "^2.1.6",`
> 
> `yarn add apollo-client` resolved it.

Wow, this fixed my issue also! Thanks!

**Comment by aadamsx** [comment]
> yarn add apollo-client resolved it.

This solved it for me as well.

**Comment by mytee306** [comment]
If you're in a `typescript` project like you may fix issue by updating `tsconfig.json`, I was surprised to see the error go away.

```diff
- "target": "es2015"
+ "lib": ["es2015"]
```

**Comment by tejedamiguel6** [comment]
> yarn add apollo-client

THIS ALSO FIXED IT FOR ME! Thanks so much!
