### ISSUE TITLE
Create dist with different that supports different require methods

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/react-apollo#4]

**Comment by stubailo** [comment]
What do you mean by this one?

**Comment by jbaxleyiii** [comment]
I'd love to support a few built versions with umd, commonjs, and global exposing of ReactApollo. That way if people want to include it in a script they can. We should be able to do it all with the build tools

**Comment by stubailo** [comment]
Hmm is this something you need for your project? I feel like most people can integrate it into their existing build with browserify, webpack, meteor, etc

**Comment by jbaxleyiii** [comment]
Nope not at all! Just saw that redux did it so thought we could. No worries :). I'll close and if it comes up we can do it later

**Comment by stubailo** [comment]
Haha I don't want to shut down the ideas - just trying to see the motivation behind them!

**Comment by jbaxleyiii** [comment]
Haha didn't think you were :) but I don't think it's worth an issue for it now
