### ISSUE TITLE
Correctly importing test-utils.tsx and configuring Create React App

### ISSUE THREAD

**Issue by lewisblackwood** [apollostack/react-apollo#400]
@jbaxleyiii  thanks for providing the examples of how to test components that use Apollo!

I'm trying to use the [test utils file](https://github.com/apollostack/react-apollo/blob/master/src/test-utils.tsx) provided for testing my own app, but haven't been able to get it working - would appreciate any help 👍

My app was bootstrapped using Create React App (CRA).

The test utils file is typed, so I've followed the CRA [guide for adding flow](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow).

If you were to follow their guide, you end up with a `package.json` that looks like:

```json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "flow": "flow"
  }
```

The `package.json` for your CRA example app is:

```json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom --coverage=true",
    "eject": "react-scripts eject",
    "flow": "flow; test $? -eq 0 -o $? -eq 2"
  }
```

Do we need to replicate the `package.json` above?

You've also included a `.flowconfig` which looks like:

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*

[options]
suppress_type=$FlowIssue
```

Do we also need to include this?

I've gone ahead and replicated your current set-up with my app. However, if I try and import the test utils into my test file:

`import { MockedProvider } from '../../Utils/test-utils';`

and run: 

`npm test`

the output is:

`Cannot find module '../../Utils/test-utils' from 'App.test.js'`.

If I instead import:

`import { MockedProvider } from '../../Utils/test-utils.tsx';`

the output is:

```   
import * as React from 'react';
    ^^^^^^
SyntaxError: Unexpected token import
```

How can I correctly import the test-utils file and use with my app?

By the way, if I clone your example app, `npm install` and then `npm test`, the output is:

``` 
FAIL  src/Pokemon.test.js
● Test suite failed to run

Couldn't find preset "react-native" relative to directory "lewisblackwood/react-apollo"
```

so I'm not yet able to run tests for the example.

**Comment by tmeasday** [comment]
Did you try this?

```js
import { MockedProvider } from 'react-apollo/lib/test-utils';
```

**Comment by lewisblackwood** [comment]
I didn't! I've just tried it, that didn't work but this did:

`import { MockedProvider } from 'react-apollo';`

Thanks a lot!

I'll carry on from here and report any further issues.

Will there be any docs written around using the test-utils? I'd be keen to contribute 👍

**Comment by lewisblackwood** [comment]
Apologies, you were correct with:

`import { MockedProvider } from 'react-apollo/lib/test-utils';`

The issue I was having was that `npm update` didn't update to the wanted version of `react-apollo` (0.8.1).

I followed the instructions [here](https://www.danieldunderfelt.com/updating-node-modules/) to update packages to their most recent versions - I can now import `MockedProvider` and run the tests.

**Comment by tmeasday** [comment]
> Will there be any docs written around using the test-utils? I'd be keen to contribute 👍

This sounds like a good idea!
