### ISSUE TITLE
react-dom peerDependency

### ISSUE THREAD

**Issue by brentvatne** [apollostack/react-apollo#402]
### Buggy Behavior

react-apollo has a peerDependency on react-dom, so you get a warning when installing it with react-native.

### Expected Behavior

No warning ;)

### Version
- apollo-client@0.8.1
- react-apollo@0.6.0

**Comment by jbaxleyiii** [comment]
@brentvatne there isn't really a way around this? We use react-dom for SSR support as part of the library.

**Comment by stubailo** [comment]
Would an optional dependency work here?

**Comment by brentvatne** [comment]
@jbaxleyiii - maybe `react-dom-apollo` in that case? or optional dependency

**Comment by craigambrose** [comment]
This seemed to appear as an error in react-apollo 0.7.3. It's really annoying on react-native.
