### ISSUE TITLE
loading prop is already false while data is not yet available

### ISSUE THREAD

**Issue by wmertens** [apollostack/react-apollo#422]
## Steps to Reproduce

1. Use `@graphql` to load a biggish dataset into `dataSet`
2. Observe `data.loading` and `data.dataSet` props
3. Render component when `data.loading` is false

### Buggy Behavior

When `data.loading` is `false`, `data.dataSet` is not immediately available

### Expected Behavior

`data.loading` should only go `false` once at least the non-deferred parts of `data.dataSet` are available to the component.

This allows you, in `render()`, to test for `loading` first and bail out with a spinner, and then if the query result is  falsy you can show a "data not found" UI. With the current behavior, this setup results in a spinner, followed by a "data not found", followed by the actual component.

### Version
- apollo-client@0.7.3
- react-apollo@0.8.1

**Comment by tmeasday** [comment]
Can you provide a reproduction of this? It seems surprising.

**Comment by wmertens** [comment]
PEBKAC! 😊  I was destructuring my `loading` prop outside the `data` prop 🙄
