### ISSUE TITLE
Update peerDependency on apollo-client

### ISSUE THREAD

**Issue by lukasvan3l** [apollostack/react-apollo#424]
## Steps to Reproduce

`react-apollo` has a peerDependency on `apollo-client: ^0.6.0`, see https://github.com/apollostack/react-apollo/blob/master/package.json#L68.

`apollo-client` is already at 0.7.3, so I'd expect the peerDependency to be updated to include ^0.7.0.

### Version
- apollo-client@0.7.3
- react-apollo@0.8.1

**Comment by 0x6e6562** [comment]
I think that #427 might be solved by this an uprev.

**Comment by 0x6e6562** [comment]
Does this issue duplicate #415 ?

**Comment by lukasvan3l** [comment]
Yesss duplicate indeed! Stupid I didn't find that one.
