### ISSUE TITLE
apollo-client/index has no exported member 'MutationBehavior'

### ISSUE THREAD

**Issue by peitalin** [apollostack/react-apollo#431]
## Steps to Reproduce

1)  Compile with webpack
Results in error message:
ERROR in [at-loader] node_modules/react-apollo/lib/graphql.d.ts:3:10
    Module '"/Users/peitalin/Downloads/Torrents/react/apollo_pokedex/node_modules/apollo-client/index"' has no exported member 'MutationBehavior'

### Expected Behavior

No error message.

### Version
Package versions:
    "apollo-client": "^0.8.0",
    "react-apollo": "^0.8.3",

**Comment by shanehyde** [comment]
I have this issue as well, did you fix it?  Or find a waorkaround?

**Comment by peitalin** [comment]
I'm not sure, I deleted node_modules and reinstalled all packages and it resolved itself.
