### ISSUE TITLE
UNMET PEER DEPENDENCY: apollo-client@0.7.3

### ISSUE THREAD

**Issue by arjunpola** [apollostack/react-apollo#434]
## Steps to Reproduce

When following the getting started for react-native by running the following command

`npm install apollo-client react-apollo graphql-tag --save`

I see the following **UNMET PEER DEPENDENCY** error

<img width="699" alt="screen shot 2017-01-24 at 11 10 50 pm" src="https://cloud.githubusercontent.com/assets/4324936/22281211/76f33d8a-e28a-11e6-88d8-a33430d5de22.png">

### Version
- apollo-client@0.7.3
- react-apollo@0.8.3

**Comment by arjunpola** [comment]
I could get it to work by using the following version

**_npm install apollo-client@0.6.0 react-apollo graphql-tag --save_**

**Comment by abhiaiyer91** [comment]
Apollo Client is at `0.8.0` @jbaxleyiii any reason why we're keeping the peer dependency at 0.6.0?

**Comment by abhiaiyer91** [comment]
@arjunpola You shouldnt be blocked even with that peer dependency. We just need to know if theres any blockers using 0.8.0 with current version of react-apollo

**Comment by jsiwhitehead** [comment]
I'm trying to use 0.8.0 with the latest version of react-apollo, and getting an error from it trying to access the removed resultBehaviors feature:

"node_modules/apollo-client/index"' has no exported member 'MutationBehavior'"

**Comment by helfer** [comment]
Hi all, I've updated the package to use apollo-client 0.8.0 now. Let me know if it doesn't work for you.
