### ISSUE TITLE
Unknown fragment Error [HELP WANTED]

### ISSUE THREAD

**Issue by okbel** [apollostack/react-apollo#435]
# Unknown fragment Error

I'm getting this error `Unknown fragment commentView`. I have the following structure.

Component.js

```js
export default compose(
  connect(mapStateToProps, mapDispatchToProps),
  postComment,
  postAction,
  deleteAction,
  queryStream
)(Component);
```

Actions.js

```js
import commentView from '../fragments/commentView.graphql';

export const queryStream = graphql(STREAM_QUERY, {
  options: () => ({
    fragments: [commentView],
    variables: {
      asset_url: url
    }
  })
});
```

```js
fragment commentView on Comment {
    id
    body
    created_at
    user {
        id
        name: displayName
        settings {
            bio
        }
    }
    actions {
        type: action_type
        count
        current: current_user {
            id
            created_at
        }
    }
}
```
This inline method (http://dev.apollodata.com/react/fragments.html) is not useful fot my case. 
I tried to use `createFragment` but it has been deprecated. I don't know what else can I try.

Note: I'm using Webpack for `.graphql` files.

Am I doing something wrong here? Feedback, Solutions and Helpful links will be extremely appreciated.

Thank you!

**Comment by okbel** [comment]
Fixed! https://dev-blog.apollodata.com/webpacking-your-graphql-documents-bf9697ed259b#.hhyutip3w

I added this `#import "./CommentsPageComment.graphql"` on the top of each `.graphql` file

I'd gladly submit a PR or collaborate to build a strong documentation.

We are setting up Apollo in @coralproject. We are looking forward to contribute in the future!

Thanks!

**Comment by tmeasday** [comment]
@okbel - great! I think some docs PRs would be super!
