### ISSUE TITLE
graphql ignores variables passed by react-router v4 params.

### ISSUE THREAD

**Issue by peitalin** [apollostack/react-apollo#437]
I'm stumped as to why graphql seems to ignore variables passed to it by react-router params.

## Steps to Reproduce

I've setup a small demo here:
https://github.com/peitalin/react_apollo_reactrouter_v4_test

### Buggy Behavior

I'm attempting to pass router params to graphql as variables.

However graphql is ignoring variables supplied to the query.

The resulting error message is:
Uncaught Error: The operation 'PokeQuery' wrapping 'PokemonPage' is expecting a variable: 'name' but it was not found in the props passed to 'Apollo(PokemonPage)'

### Expected Behavior

React-router passes pokemon name to graphql via ownProps.params.name, and the query succeeds

### Version
    "apollo-client": "^0.8.0",
    "graphql-tag": "^1.2.3",
    "react-apollo": "^0.8.3",
    "react-router": "next"

**Comment by tmeasday** [comment]
It's a typo: https://github.com/peitalin/react_apollo_reactrouter_v4_test/blob/master/src/components/PokemonPage.tsx#L48 should be `variables`.

**Comment by tmeasday** [comment]
Perhaps the error message here could be clearer?

**Comment by peitalin** [comment]
No, should be fine, I just somehow missed that.
