### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by mattiasewers** [apollostack/react-apollo#45]
Does react-apollo not support multiple queries or is it graphql?

**Comment by stubailo** [comment]
It depends on what you mean by "multiple queries". What are you trying to do?

**Comment by mattiasewers** [comment]
@stubailo I am trying to query something like this `query { user{} project{} }` got an error saying `Error: Multiple root queries, cannot print that yet.`

**Comment by stubailo** [comment]
@mattiasewers as a short-term workaround, you can pass `forceFetch: true` in your container. Opened an issue on apollo-client, going to close here since there isn't anything `react-apollo` can do about it.

**Comment by stubailo** [comment]
Should be fixed now - just update to apollo-client 0.3.3, and let me know if it works!

**Comment by mattiasewers** [comment]
Yes, works great! Thanks!
