### ISSUE TITLE
returnPartialData throws error on empty store

### ISSUE THREAD

**Issue by NeoPhi** [apollostack/react-apollo#46]
If in `mapQueriesToProps` I specify `returnPartialData: true` I get an error thrown from `diffFieldAgainstStore` saying that `Uncaught Error: Can't find field viewer on object [object Object].`. I would expect an undefined object to be returned to the view if no data was in the store and `returnPartialData` was set to true.

**Comment by stubailo** [comment]
Closing in favor of: https://github.com/apollostack/apollo-client/issues/193

**Comment by stubailo** [comment]
This should be fixed in Apollo Client 0.3.5. Please let me know if it isn't!
