### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/react-apollo#55]
Dears, this is more of a question than issue.

Current functionality maps the query to react component. This, whenever is displayed fetches new data from the server. While this is OK for many cases, it would be great to have a decision mechanism to use cached data. For example, I can cache data in the store and then in the container I can decide whether to use cached data or get fresh data.

Do you have any advice on implementation?

In the [core](http://docs.apollostack.com/apollo-client/core.html) I've found a way of how to perform a query, but there are just too many possibilities on how to approach this. Would love to hear from you guys.

**Comment by jbaxleyiii** [comment]
@tomitrescak react-apollo does the caching behind the scenes. As long as you aren't specifically adding in `forceFetch: true` to your query object, the wrapper component will pull cached data from the store if it exists

**Comment by tomitrescak** [comment]
Thanks for the reply. That's fantastic news! Is this process described somewhere? I just want to understand how it works. Does it cache  data per text of the query? Where in store are the data stored? I'll try to look I to sources.

**Comment by jbaxleyiii** [comment]
@tomitrescak yep! React-apollo uses the core's `watchQuery` method under the hood. The section about query diffing (the caching mechanism we use) is [here](http://docs.apollostack.com/apollo-client/core.html#forceFetch). It is stored under the apollo redux key (default is `apollo`) then under a data key.
