### ISSUE TITLE
Unexpected APOLLO_QUERY_ERROR fired due to bug in render

### ISSUE THREAD

**Issue by NeoPhi** [apollostack/react-apollo#58]
If I have an error in the render function of a component that is receiving data from the apollo-client, I see that an `APOLLO_QUERY_ERROR` action is fired and the bug is captured as the `networkError`, even though the query did run successfully. An unhandled Promise error is also thrown. The following console output is from Chrome 50:

```
 action @ 08:27:23.412 APOLLO_QUERY_INIT 
 prev state Object {apollo: Object}
 action Object {type: "APOLLO_QUERY_INIT", queryString: "query sample {↵  viewer {↵    name↵  }↵}↵", query: Object, minimizedQueryString: "query sample {↵  viewer {↵    name↵  }↵}↵", minimizedQuery: Object…}
 next state Object {apollo: Object}

 action @ 08:27:23.435 APOLLO_QUERY_RESULT 
 prev state Object {apollo: Object}
 action Object {type: "APOLLO_QUERY_RESULT", result: Object, queryId: "0", requestId: 1}
 next state Object {apollo: Object}

 action @ 08:27:23.446 APOLLO_QUERY_ERROR 
 prev state Object {apollo: Object}
 action Object {type: "APOLLO_QUERY_ERROR", error: TypeError: Cannot read property 'name' of undefined
    at BadComponent (http://localhost:3000/bundl…, queryId: "0", requestId: 1}
 next state Object {apollo: Object}

Unhandled promise rejection TypeError: Cannot read property 'name' of undefined(…)
```

I have a simple in-memory example that demonstrates this behavior: https://github.com/NeoPhi/apollo-playground/tree/apollo-error

**Comment by jbaxleyiii** [comment]
@NeoPhi I still haven't been able to replicate this super well (even in the repro I couldn't get it to work). I know this is a bug however! I'm going to close this in favor of #57 and I have hope that #29 will fix it!
