### ISSUE TITLE
mapStatesToProps() NOT working in the latest version.

### ISSUE THREAD

**Issue by saeho** [apollostack/react-apollo#60]
mapStateToProps() does not work in React-Apollo connect().

The redux state changes are triggered and the change triggers the mapStatesToProps() function. However it stops there.

After hitting the mapStatesToProps(), the changed states do not get passed as props to the underlying components.

**Comment by jbaxleyiii** [comment]
Do you have a reproduction? I added a test to verify that redux changes do pass to the child component here: https://github.com/apollostack/react-apollo/commit/18e65145466cac22de476916030e599ed5bed313

**Comment by saeho** [comment]
It might only fail when the redux mapStateToProps() is used together with mapQueriesToProps(). As is the case for me. I have not tested mapStateToProps() alone yet. When used together they both work, however the props do not get passed down to the component (despite the dispatch working and the result of dispatch hitting the mapStateToProps() successfully).

**Comment by jbaxleyiii** [comment]
@saeho I added some more tests to see if I can replicate (https://github.com/apollostack/react-apollo/commit/69921f6f021e1825503a450ea8fd2865fb469c19). I still can't seem to replicated it. Do you have anything you can share to help?

**Comment by saeho** [comment]
Actually, I think this might be a react-native issue. Since React Native .26, when they split the Component class from React Native back to React, mapStateToProps() behaved differently.

**Comment by saeho** [comment]
Question for you.

Why are you importing connect from 'react-redux'?

Since this is Apollo and attempting to use mapStateToProps() and mapQueriesToProps() together, shouldn't you be importing connect from 'react-apollo' ?

**Comment by stubailo** [comment]
It's kind of unfortunate that there are so many react-native specific bugs. I would have hoped that it would be more similar to a browser-based React environment.

**Comment by saeho** [comment]
Well, it may or may not be. Actually there's a very good chance I'm wrong, after all React Native works extremely well with all react packages, including Apollo.

I don't have time to investigate to see if it is RN or not at this immediate time however.

Can you please tell me why jbaxley used connect() imported from 'react-redux' and not 'react-apollo'?

**Comment by jbaxleyiii** [comment]
@saeho where do you see me doing that?

**Comment by jbaxleyiii** [comment]
@stubailo looks like its time to figure out a way to test in react native 👍

**Comment by saeho** [comment]
line 7 in your example

https://github.com/apollostack/react-apollo/blob/69921f6f021e1825503a450ea8fd2865fb469c19/test/connect/queries.tsx#L7

**Comment by jbaxleyiii** [comment]
@saeho I'm only using that to test `react-apollo` connect against `react-redux`. In the test I added to verify this, I'm using `connect` which comes from react-apollo aside from `ReactReduxConnect` which is how I'm importing connect from redux

**Comment by saeho** [comment]
Hello folks, I'd like to apologize.

I mistyped mapStateToProps(). I wrote the function name as "mapStatesToProps" (notice the plural on States). This issue was my fault.

**Comment by stubailo** [comment]
Oh gosh! I bet there is some way we can catch that and print an error, lol
