### ISSUE TITLE
for queries with forceFetch: true that have already been subscribed to, loading should initially be true

### ISSUE THREAD

**Issue by hamzapurra** [apollostack/react-apollo#63]
![screen shot 2016-05-27 at 3 19 08 am](https://cloud.githubusercontent.com/assets/1947927/15593235/60bab180-23bb-11e6-8e60-87b8a0de8b78.png)

**Comment by jbaxleyiii** [comment]
Fixed in https://github.com/apollostack/react-apollo/pull/66
