### ISSUE TITLE
loading is true for mutations that haven't been invoked yet

### ISSUE THREAD

**Issue by hamzapurra** [apollostack/react-apollo#64]
![screen shot 2016-05-27 at 1 46 27 am](https://cloud.githubusercontent.com/assets/1947927/15593576/b6ce331e-23be-11e6-895d-e1351c2a27e1.png)

**Comment by inyono** [comment]
Same for me. I scanned over the code and tests and found this: https://github.com/apollostack/react-apollo/blob/master/test/connect/mutations.tsx#L84. According to the test, `loading: true` before invocation is intended.

**Comment by jbaxleyiii** [comment]
Thanks for pointing this out! Originally the query data and mutation data (defaults) had the same state. It doesn't make a lot of sense on the mutation side. Fixed here: https://github.com/apollostack/react-apollo/pull/65

**Comment by deoqc** [comment]
@jbaxleyiii I'm seeing this same issue again.
