### ISSUE TITLE
mapMutationsToProps don't automatically subscribe to store changes

### ISSUE THREAD

**Issue by deoqc** [apollostack/react-apollo#68]
I believe the `mapMutationsToProps` don't have the state updated unless the `mapStateToProps` is also present.

To be precise, I have an [redux-form](https://github.com/erikras/redux-form) that I use the state for input in my `mapMutationsToProps`. When no `mapStateToProps` is present, `APOLLO_MUTATION_INIT` action has empty `variables`, due to the emptiness of the initial form state. If I use `mapStateToProps`, the `variables` is correct with the updated state.

**updated**: also I had to use `mapStateToProps = (state) => ({form: state.form})`. I believe that whenever the form gets updated, the component re-render and it makes the `mapMutationsToProps` be updated with the newest state.

**Comment by jbaxleyiii** [comment]
@deoqc yep that sounds like a lifecycle bug due to our methods to re-renders. I'll take a look and try to get it fixed asap!

**Comment by jbaxleyiii** [comment]
@deoqc I actually already have a test covering what I think you are describing: https://github.com/apollostack/react-apollo/blob/master/test/connect/mutations.tsx#L486-L579

Do you have a sample of how you have it setup where its not working?

The linked test covers if the store changes (outside of `apollo`'s internal data), then when the mutation is actually called it checks to ensure it has the correct data. That sounds like the issue you are having?

**Comment by deoqc** [comment]
@jbaxleyiii that sound's like it. I will try to reproduce it.

**Comment by jbaxleyiii** [comment]
@deoqc is this still a problem?

**Comment by deoqc** [comment]
Sorry for leaving this open.
The problem - as usual with Apollo - faded away. =)
