### ISSUE TITLE
Wrong props passed to `mapQueriesToProps` and `mapMutationsToProps` on store change

### ISSUE THREAD

**Issue by sgoll** [apollostack/react-apollo#69]
In connect's `bindStoreUpdate` method, `this.props` is bound only once:

https://github.com/apollostack/react-apollo/blob/69ce020acbc6b21e43def5e1eca1f36f263e353f/src/connect.tsx#L202

Whenever `this.subscribeToAllQueries` and `this.createAllMutationHandlers` are called further down in this method due to store state changes, they receive the probably outdated props bound on initialisation instead of the current value of `this.props`.

Should I prepare a pull request to fix this?

**Comment by jbaxleyiii** [comment]
@sgoll do you have a replication that shows the outdated props? We have a few tests to ensure that the correct props are passed to the map functions

**Comment by sgoll** [comment]
Yep, it happens in our current project. I'll write up a minimal example tonight.

**Comment by sgoll** [comment]
@jbaxleyiii I created a minimal test that replicates the behavior; the test fails at line 79 where the original prop value "foo" is passed to `mapQueriesToProps` again despite not actually having been changed:

https://gist.github.com/sgoll/8519d638feb9489242f517cf954e4681

**Comment by jbaxleyiii** [comment]
@sgoll fantastic replication! I'll take a look and try to get a fix out today!

**Comment by jbaxleyiii** [comment]
Also thanks so much @sgoll for the fantastic test reproduction!

Fixed via https://github.com/apollostack/react-apollo/pull/70 in `0.3.8`
