### ISSUE TITLE
typescript typings broken?

### ISSUE THREAD

**Issue by AlmaasAre** [apollostack/react-apollo#74]
![image](https://cloud.githubusercontent.com/assets/1777366/16154079/8c451c10-34a9-11e6-899b-3b98a57afaf8.png)

When installing the project with npm, it seems like the typings-folder is not included.

**Comment by jbaxleyiii** [comment]
@AlmaasAre interesting! Is this something you would be able to open a PR and fix?

**Comment by AlmaasAre** [comment]
sure @jbaxleyiii
