### ISSUE TITLE
Loading component

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/react-apollo#76]
Currently it is possible to compose components in a way that we show "loading" text when apollo is querying data, based on the "loading" flag.

What would be great it to have a possibility to specify a second component in the connect method, and when this component is specified it would render that component instead of the original one.

Example:

```
connect({ mapQueriesToProps, mapStateToProps })(MyComponent, LoadingComponent) 
```

Would you consider this?

**Comment by stubailo** [comment]
I'm personally not a fan of building this in directly, but I bet we could get pretty far with a small separate module that just handles showing a loading state. Curious what others think.

**Comment by helfer** [comment]
I think this is more appropriately handled inside the component. If you want, you could write a small function that takes two components, and returns a single one that does what you describe.

**Comment by tomitrescak** [comment]
@helfer I actually tried that, but I failed as I could not access the loading flag. Do you have any snippet I could use? Thanks.
Currently I solve it in components as you guys say, but it is a lot of repeated boilerplate for 20+ components in my app.

**Comment by helfer** [comment]
Does something along these lines not work?

```
function makeLoadingComponent(loadingComponent, component){
  return function({ data, ...args }){
    if(data.loading) {
      return loadingComponent({ data, ...args });
    } else {
      return component({ data, ...args });
    }
  }
}
```

**Comment by tomitrescak** [comment]
@helfer looks fine! Thanks!
