### ISSUE TITLE
npm package doesn't use dist/index.js

### ISSUE THREAD

**Issue by AlmaasAre** [apollostack/react-apollo#79]
Seems like the npm-package uses unconcatinated index.js and not the one in dist?

![image](https://cloud.githubusercontent.com/assets/1777366/16262816/9ccf2834-3871-11e6-842b-1332b4d3b245.png)

**Comment by jbaxleyiii** [comment]
@AlmaasAre we use the the dist to get a read of the filesize of the library. The build tools move the compiled code from `/lib/src` to the root level when publishing to npm
