### ISSUE TITLE
this.queryHandles keys refers to query options instead of actual WatchedQueryHandle

### ISSUE THREAD

**Issue by lgollut** [apollostack/react-apollo#8]
`mapQueriesToProps` seems to be initially designed to call `watchQuery(options)` in bde5a2ce49286660bce51adad4b29eb12ff2ead5 but is implemented without passing the function. `this.queryHandles` hence only contains queries options and `unsubcribeAllQueries()` fails on `this.queryHandles[key].stop()`

**Comment by jbaxleyiii** [comment]
@lgollut we actually changed the API and removed the `watchQuery` as part of the argument object. Curious, what do you need the handle for?

I'll add in a way to access the individual handles by key though!
