### ISSUE TITLE
Development process

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-apollo#81]
I'm trying to slightly modify the `forceFetch` behaviour in order to respect the changes in this PR:  https://github.com/apollostack/apollo-client/pull/309

But I can't get this project to build with the new typings from `apollo-client`. @jbaxleyiii can you fill me in on how I'm supposed to bring typings over from `apollo-client`? I ran `node_modules/.bin/typings install` but it just brought a bunch of new `apollo-client` related errors.

**Comment by jbaxleyiii** [comment]
@tmeasday well thats no good! I'll take a look and see if I can figure out whats going on!

**Comment by jbaxleyiii** [comment]
@tmeasday fixed in https://github.com/apollostack/react-apollo/pull/75/commits/d4c3d03dfcaa8b2c08c8f35c016fe176d4938856 

That PR should also fix #80 and #72

**Comment by tmeasday** [comment]
Oh, I think I figured out the issue I was having. I needed to symlink `apollo-client/gql.d.ts` into `lib/src`. @stubailo we should document this somewhere.
