### ISSUE TITLE
Apparent redundant check in `connect` file

### ISSUE THREAD

**Issue by leoasis** [apollostack/react-apollo#82]
Hi! First of all great work on the whole apollo platform, following this with high excitement!

I'm just starting to get into the code, debugging the GitHunt app and seeing how things work under the hood. While I was poking around the code in `connect`, I found this check that I think evaluates to true all the time it is reached, because of the way `oldQueries` is defined a couple of lines above:
https://github.com/apollostack/react-apollo/blob/master/src/connect.tsx#L241

I'm not sure of the impact of this, I think it's not that big, but maybe it is, and since I'm just getting started to understand all this I'm not sure right now. Anyway, since I saw this, maybe it's useful for you to quickly see if this is ultimately a big issue or not.

Sorry to bother you with this if it happens to be a trivial thing! And again thanks for all the work you've put on this!

**Comment by jbaxleyiii** [comment]
hey @leoasis! Glad you are exploring apollo!

That check was added due to some oddities in the testing system. It should always be true in actual usage. I need to refactor the tests (sometimes it was coming in as `undefined` for some reason) which should allow the removal of it!

Thanks!

**Comment by leoasis** [comment]
Thanks for the response @jbaxleyiii! Got it (still seems like that `assign` will never return `undefined`, unless as you say, the testing environment is mocking it or something weird), thanks for the explanation, and will definitely keep playing and considering for some real work to be done anytime soon!

Again thanks for all the work
