### ISSUE TITLE
Support immutable.js

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/react-apollo#87]

**Comment by Aweary** [comment]
Quoting relevant comment from here: https://github.com/apollostack/react-apollo/issues/78#issuecomment-229407444

>
Does it make more sense to provide a way for the user to map their `storeState` to `connect`'s local state? If you just add a check for immutable.js you'll still have the same problem when users are using other immutable libraries.

> Instead maybe connect can accept a function like `getStateFromStoreState` that passes in `storeState` and lets the user parse and return a plain object representing their state.

**Comment by Glavin001** [comment]
Any progress on this? Thanks!

**Comment by Aweary** [comment]
I'd be happy to get a PR going for my suggestion, if it sounds good to the Apollo team 👍

**Comment by jbaxleyiii** [comment]
@Aweary I'm assuming this would need to be supported in the client as well? If you can do a PR and/or provide a gist of using immutable.js with redux I can get it going

**Comment by jbaxleyiii** [comment]
@Aweary the new API doesn't do any store copying so it should support immutable 👍
