### ISSUE TITLE
Cannot find module 'graphql/language/printer'

### ISSUE THREAD

**Issue by Vanuan** [apollostack/react-apollo#91]
Following steps to test locally:

```
npm install
npm test
```
```

 npm run test

> react-apollo@0.3.12 pretest /react-apollo
> npm run compile


> react-apollo@0.3.12 compile /react-apollo
> tsc


3 import { print } from 'graphql/language/printer';
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/apollo-client/index.d.ts(3,23): error TS2307: Cannot find module 'graphql/language/printer'.


npm ERR! node v4.2.2
npm ERR! npm  v3.7.5

```

How to fix it?

**Comment by Vanuan** [comment]
npm shrinkwrap is missing. Probably some package has got updated.

**Comment by helfer** [comment]
I think `apollo-client` no longer depends directly on graphql, so the import should come from `graphql-tag`. I'm a bit surprised that this has already made it into `react-apollo` though...

**Comment by Vanuan** [comment]
So this is a bug in apollo-client, not in react-apollo.
Temporary fix: https://github.com/Vanuan/react-apollo/commit/c2ff016d18d01bc7af19a7465fd72edbf426cca8

I.e. apollo-client 0.3.26 has got this problem.

**Comment by Vanuan** [comment]
Looks to be fixed by https://github.com/apollostack/apollo-client/pull/357/files
