### ISSUE TITLE
Pass through resultBehaviors option to `mutate`

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-apollo#93]
We added a new feature to mutations in ApolloClient, and it's not being passed through by `react-apollo`.

By the way, is there any reason we don't just pass through all of the options? It seems like an unnecessary step to need to update react-apollo whenever we add new options.

**Comment by jbaxleyiii** [comment]
@stubailo originally we didn't because we didn't want to pass `watchQuery` through. However, I'm good to pass everything down!

**Comment by stubailo** [comment]
Sounds good to me!

**Comment by stubailo** [comment]
This wasn't fixed - what I meant is that `react-apollo` only uses the `variables` and `mutation` options when calling `client.mutate`, even if more options were passed. We should pass in any options the user provides to the `mutate` call.

**Comment by stubailo** [comment]
Slava will add a PR for this in a bit.

**Comment by jbaxleyiii** [comment]
@stubailo are you good with me rolling this into the 0.4.0?

**Comment by stubailo** [comment]
Oh so we already fixed this and published a new version. so it's all good!

**Comment by brunolemos** [comment]
I'm new to Apollo. There is this code in the saikat/react-apollo-starter-kit repo:

```js
<button onClick={async () => {
    // This is temporary until https://github.com/apollostack/react-apollo/issues/93 is done
    let mutationResult = await mutations.addCount(1)
    if (mutationResult) data.refetch()
}}>
```

What should be the new code now that this issue is closed?

**Comment by stubailo** [comment]
Hey, probably best to ask @saikat. I haven't really looked at that code myself.
